// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"
)

const accountExists = `-- name: AccountExists :one
SELECT COUNT(*) > 0 FROM accounts
`

func (q *Queries) AccountExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, accountExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (id, email, password_hash)
VALUES (?, ?, ?)
`

type CreateAccountParams struct {
	ID           string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const getAccountByEmail = `-- name: GetAccountByEmail :one
SELECT id, email, password_hash, created_at, updated_at
FROM accounts
WHERE email = ?
`

func (q *Queries) GetAccountByEmail(ctx context.Context, email string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByEmail, email)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, email, password_hash, created_at, updated_at
FROM accounts
WHERE id = ?
`

func (q *Queries) GetAccountByID(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE accounts
SET password_hash = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateAccountPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountPassword, arg.PasswordHash, arg.ID)
	return err
}
