// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlc

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, task_id, filename, content_type, size, storage_path, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID          string
	TaskID      string
	Filename    string
	ContentType string
	Size        int64
	StoragePath string
	CreatedBy   string
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.TaskID,
		arg.Filename,
		arg.ContentType,
		arg.Size,
		arg.StoragePath,
		arg.CreatedBy,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ? AND task_id = ?
`

type DeleteAttachmentParams struct {
	ID     string
	TaskID string
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.TaskID)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, task_id, filename, content_type, size, storage_path, created_by, created_at
FROM attachments WHERE id = ?
`

func (q *Queries) GetAttachment(ctx context.Context, id string) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Filename,
		&i.ContentType,
		&i.Size,
		&i.StoragePath,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT id, task_id, filename, content_type, size, storage_path, created_by, created_at
FROM attachments WHERE task_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAttachments(ctx context.Context, taskID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Filename,
			&i.ContentType,
			&i.Size,
			&i.StoragePath,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
