// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlc

import (
	"context"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT COUNT(*) FROM audit_log
WHERE org_id = ?1
  AND (?2 IS NULL OR action = ?2)
  AND (?3 IS NULL OR actor_id = ?3)
`

type CountAuditEntriesParams struct {
	OrgID         string
	ActionFilter  interface{}
	ActorIDFilter interface{}
}

func (q *Queries) CountAuditEntries(ctx context.Context, arg CountAuditEntriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditEntries, arg.OrgID, arg.ActionFilter, arg.ActorIDFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (id, org_id, actor_id, action, entity_type, entity_id, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateAuditEntryParams struct {
	ID         string
	OrgID      string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	Metadata   string
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditEntry,
		arg.ID,
		arg.OrgID,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	return err
}

const deleteAuditEntriesOlderThan = `-- name: DeleteAuditEntriesOlderThan :execrows
DELETE FROM audit_log WHERE created_at < ?1
`

// Audit log retention. Deletes entries older than the cutoff timestamp
// across all orgs. Called by the periodic retention cleanup goroutine.
func (q *Queries) DeleteAuditEntriesOlderThan(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAuditEntriesOlderThan, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT a.id, a.org_id, a.actor_id, a.action, a.entity_type, a.entity_id,
       a.metadata, a.created_at,
       u.name AS actor_name, u.email AS actor_email
FROM audit_log a
JOIN users u ON u.id = a.actor_id
WHERE a.org_id = ?1
  AND (?2 IS NULL OR a.action = ?2)
  AND (?3 IS NULL OR a.actor_id = ?3)
ORDER BY a.created_at DESC
LIMIT ?5
OFFSET ?4
`

type ListAuditEntriesParams struct {
	OrgID         string
	ActionFilter  interface{}
	ActorIDFilter interface{}
	OffsetVal     int64
	LimitVal      int64
}

type ListAuditEntriesRow struct {
	ID         string
	OrgID      string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	Metadata   string
	CreatedAt  string
	ActorName  string
	ActorEmail string
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEntries,
		arg.OrgID,
		arg.ActionFilter,
		arg.ActorIDFilter,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEntriesRow
	for rows.Next() {
		var i ListAuditEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
