// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"
)

const createComment = `-- name: CreateComment :exec
INSERT INTO comments (id, org_id, task_id, project_id, author_id, content, parent_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCommentParams struct {
	ID        string
	OrgID     string
	TaskID    string
	ProjectID string
	AuthorID  string
	Content   string
	ParentID  *string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.ID,
		arg.OrgID,
		arg.TaskID,
		arg.ProjectID,
		arg.AuthorID,
		arg.Content,
		arg.ParentID,
	)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.org_id, c.task_id, c.project_id, c.author_id, c.content, c.parent_id,
       c.created_at, c.updated_at, c.edited_at, c.deleted_at,
       u.name AS author_name, u.email AS author_email, u.avatar_url AS author_avatar_url
FROM comments c
INNER JOIN users u ON u.id = c.author_id
WHERE c.id = ? AND c.org_id = ? AND c.deleted_at IS NULL
`

type GetCommentByIDParams struct {
	ID    string
	OrgID string
}

type GetCommentByIDRow struct {
	ID              string
	OrgID           string
	TaskID          string
	ProjectID       string
	AuthorID        string
	Content         string
	ParentID        *string
	CreatedAt       string
	UpdatedAt       string
	EditedAt        *string
	DeletedAt       *string
	AuthorName      string
	AuthorEmail     string
	AuthorAvatarUrl *string
}

func (q *Queries) GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (GetCommentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCommentByID, arg.ID, arg.OrgID)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TaskID,
		&i.ProjectID,
		&i.AuthorID,
		&i.Content,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EditedAt,
		&i.DeletedAt,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorAvatarUrl,
	)
	return i, err
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT c.id, c.org_id, c.task_id, c.project_id, c.author_id, c.content, c.parent_id,
       c.created_at, c.updated_at, c.edited_at, c.deleted_at,
       u.name AS author_name, u.email AS author_email, u.avatar_url AS author_avatar_url
FROM comments c
INNER JOIN users u ON u.id = c.author_id
WHERE c.task_id = ?
  AND c.org_id = ?
  AND c.deleted_at IS NULL
  AND (?3 = '' OR c.created_at < ?3)
ORDER BY c.created_at DESC
LIMIT ?
`

type ListCommentsByTaskParams struct {
	TaskID       string
	OrgID        string
	BeforeCursor interface{}
	Limit        int64
}

type ListCommentsByTaskRow struct {
	ID              string
	OrgID           string
	TaskID          string
	ProjectID       string
	AuthorID        string
	Content         string
	ParentID        *string
	CreatedAt       string
	UpdatedAt       string
	EditedAt        *string
	DeletedAt       *string
	AuthorName      string
	AuthorEmail     string
	AuthorAvatarUrl *string
}

// Paginated: returns the newest @limit comments older than @before_cursor
// (or the newest @limit if before_cursor is empty). Ordered ASC so the
// thread reads top-to-bottom. Pass the oldest loaded created_at as the
// next before_cursor to load the previous page.
// Org-scoped (org_id) so a foreign-org task_id cannot be used to read comments.
func (q *Queries) ListCommentsByTask(ctx context.Context, arg ListCommentsByTaskParams) ([]ListCommentsByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByTask,
		arg.TaskID,
		arg.OrgID,
		arg.BeforeCursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsByTaskRow
	for rows.Next() {
		var i ListCommentsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TaskID,
			&i.ProjectID,
			&i.AuthorID,
			&i.Content,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = datetime('now'), updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type SoftDeleteCommentParams struct {
	ID    string
	OrgID string
}

func (q *Queries) SoftDeleteComment(ctx context.Context, arg SoftDeleteCommentParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteComment, arg.ID, arg.OrgID)
	return err
}

const updateComment = `-- name: UpdateComment :exec
UPDATE comments
SET content = ?, updated_at = datetime('now'), edited_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateCommentParams struct {
	Content string
	ID      string
	OrgID   string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) error {
	_, err := q.db.ExecContext(ctx, updateComment, arg.Content, arg.ID, arg.OrgID)
	return err
}
