// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"strings"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id, org_id)
VALUES (?, ?, ?)
ON CONFLICT(conversation_id, user_id) DO NOTHING
`

type AddConversationMemberParams struct {
	ConversationID string
	UserID         string
	OrgID          string
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, addConversationMember, arg.ConversationID, arg.UserID, arg.OrgID)
	return err
}

const countConversationMembers = `-- name: CountConversationMembers :one
SELECT COUNT(*) FROM conversation_members WHERE conversation_id = ?
`

func (q *Queries) CountConversationMembers(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversationMembers, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPinnedMessages = `-- name: CountPinnedMessages :one
SELECT COUNT(*) FROM messages WHERE conversation_id = ? AND pinned = 1 AND deleted_at IS NULL
`

func (q *Queries) CountPinnedMessages(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPinnedMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChannelPermission = `-- name: CreateChannelPermission :exec
INSERT INTO channel_permissions (channel_id, role, permission, allow)
VALUES (?, ?, ?, ?)
`

type CreateChannelPermissionParams struct {
	ChannelID  string
	Role       string
	Permission string
	Allow      int64
}

func (q *Queries) CreateChannelPermission(ctx context.Context, arg CreateChannelPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createChannelPermission,
		arg.ChannelID,
		arg.Role,
		arg.Permission,
		arg.Allow,
	)
	return err
}

const createChannelProjectLink = `-- name: CreateChannelProjectLink :exec
INSERT INTO channel_project_links (channel_id, project_id) VALUES (?, ?)
ON CONFLICT(channel_id, project_id) DO NOTHING
`

type CreateChannelProjectLinkParams struct {
	ChannelID string
	ProjectID string
}

// Channel project links
func (q *Queries) CreateChannelProjectLink(ctx context.Context, arg CreateChannelProjectLinkParams) error {
	_, err := q.db.ExecContext(ctx, createChannelProjectLink, arg.ChannelID, arg.ProjectID)
	return err
}

const createChannelUserOverride = `-- name: CreateChannelUserOverride :exec
INSERT INTO channel_user_overrides (channel_id, user_id, permission, allow)
VALUES (?, ?, ?, ?)
ON CONFLICT(channel_id, user_id, permission) DO UPDATE SET allow = excluded.allow
`

type CreateChannelUserOverrideParams struct {
	ChannelID  string
	UserID     string
	Permission string
	Allow      int64
}

func (q *Queries) CreateChannelUserOverride(ctx context.Context, arg CreateChannelUserOverrideParams) error {
	_, err := q.db.ExecContext(ctx, createChannelUserOverride,
		arg.ChannelID,
		arg.UserID,
		arg.Permission,
		arg.Allow,
	)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, org_id, parent_id, name, topic, type, created_by, position_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, org_id, parent_id, name, topic, type, created_by, position_key, deleted_at, created_at, updated_at
`

type CreateConversationParams struct {
	ID          string
	OrgID       string
	ParentID    *string
	Name        string
	Topic       string
	Type        string
	CreatedBy   string
	PositionKey string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, createConversation,
		arg.ID,
		arg.OrgID,
		arg.ParentID,
		arg.Name,
		arg.Topic,
		arg.Type,
		arg.CreatedBy,
		arg.PositionKey,
	)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.CreatedBy,
		&i.PositionKey,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelPermissions = `-- name: DeleteChannelPermissions :exec
DELETE FROM channel_permissions WHERE channel_id = ?
`

func (q *Queries) DeleteChannelPermissions(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelPermissions, channelID)
	return err
}

const deleteChannelProjectLink = `-- name: DeleteChannelProjectLink :exec
DELETE FROM channel_project_links WHERE channel_id = ? AND project_id = ?
`

type DeleteChannelProjectLinkParams struct {
	ChannelID string
	ProjectID string
}

func (q *Queries) DeleteChannelProjectLink(ctx context.Context, arg DeleteChannelProjectLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelProjectLink, arg.ChannelID, arg.ProjectID)
	return err
}

const deleteChannelProjectLinks = `-- name: DeleteChannelProjectLinks :exec
DELETE FROM channel_project_links WHERE channel_id = ?
`

func (q *Queries) DeleteChannelProjectLinks(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelProjectLinks, channelID)
	return err
}

const deleteChannelUserOverrides = `-- name: DeleteChannelUserOverrides :exec
DELETE FROM channel_user_overrides WHERE channel_id = ?
`

func (q *Queries) DeleteChannelUserOverrides(ctx context.Context, channelID string) error {
	_, err := q.db.ExecContext(ctx, deleteChannelUserOverrides, channelID)
	return err
}

const deleteConversation = `-- name: DeleteConversation :exec
UPDATE conversations SET deleted_at = datetime('now') WHERE id = ? AND org_id = ?
`

type DeleteConversationParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, arg.ID, arg.OrgID)
	return err
}

const deleteConversationsByParent = `-- name: DeleteConversationsByParent :exec
UPDATE conversations SET deleted_at = datetime('now')
WHERE parent_id = ? AND org_id = ? AND deleted_at IS NULL
`

type DeleteConversationsByParentParams struct {
	ParentID *string
	OrgID    string
}

func (q *Queries) DeleteConversationsByParent(ctx context.Context, arg DeleteConversationsByParentParams) error {
	_, err := q.db.ExecContext(ctx, deleteConversationsByParent, arg.ParentID, arg.OrgID)
	return err
}

const findDMByUsers = `-- name: FindDMByUsers :one
SELECT c.id, c.org_id, c.parent_id, c.name, c.topic, c.type, c.created_by, c.position_key, c.created_at, c.updated_at, c.deleted_at FROM conversations c
INNER JOIN conversation_members requester ON requester.conversation_id = c.id AND requester.user_id = ?1
INNER JOIN conversation_members recipient ON recipient.conversation_id = c.id AND recipient.user_id = ?2
WHERE c.org_id = ?3 AND c.type = 'direct' AND c.deleted_at IS NULL
LIMIT 1
`

type FindDMByUsersParams struct {
	RequesterID string
	RecipientID string
	OrgID       string
}

type FindDMByUsersRow struct {
	ID          string
	OrgID       string
	ParentID    *string
	Name        string
	Topic       string
	Type        string
	CreatedBy   string
	PositionKey string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   *string
}

func (q *Queries) FindDMByUsers(ctx context.Context, arg FindDMByUsersParams) (FindDMByUsersRow, error) {
	row := q.db.QueryRowContext(ctx, findDMByUsers, arg.RequesterID, arg.RecipientID, arg.OrgID)
	var i FindDMByUsersRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.CreatedBy,
		&i.PositionKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelPermissions = `-- name: GetChannelPermissions :many
SELECT role, permission, allow FROM channel_permissions WHERE channel_id = ?
`

type GetChannelPermissionsRow struct {
	Role       string
	Permission string
	Allow      int64
}

// Channel permissions
func (q *Queries) GetChannelPermissions(ctx context.Context, channelID string) ([]GetChannelPermissionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelPermissions, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelPermissionsRow
	for rows.Next() {
		var i GetChannelPermissionsRow
		if err := rows.Scan(&i.Role, &i.Permission, &i.Allow); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelProjectLinks = `-- name: GetChannelProjectLinks :many
SELECT project_id FROM channel_project_links WHERE channel_id = ?
`

func (q *Queries) GetChannelProjectLinks(ctx context.Context, channelID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getChannelProjectLinks, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var project_id string
		if err := rows.Scan(&project_id); err != nil {
			return nil, err
		}
		items = append(items, project_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelUserOverrides = `-- name: GetChannelUserOverrides :many
SELECT user_id, permission, allow FROM channel_user_overrides WHERE channel_id = ?
`

type GetChannelUserOverridesRow struct {
	UserID     string
	Permission string
	Allow      int64
}

// Channel user overrides
func (q *Queries) GetChannelUserOverrides(ctx context.Context, channelID string) ([]GetChannelUserOverridesRow, error) {
	rows, err := q.db.QueryContext(ctx, getChannelUserOverrides, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelUserOverridesRow
	for rows.Next() {
		var i GetChannelUserOverridesRow
		if err := rows.Scan(&i.UserID, &i.Permission, &i.Allow); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConversationByID = `-- name: GetConversationByID :one
SELECT id, org_id, parent_id, name, topic, type, created_by, position_key, deleted_at, created_at, updated_at FROM conversations WHERE id = ? AND org_id = ?
`

type GetConversationByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetConversationByID(ctx context.Context, arg GetConversationByIDParams) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByID, arg.ID, arg.OrgID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.CreatedBy,
		&i.PositionKey,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationByIDAnyConv = `-- name: GetConversationByIDAnyConv :one
SELECT id, org_id, parent_id, name, topic, type, created_by, position_key, deleted_at, created_at, updated_at FROM conversations WHERE id = ?
`

func (q *Queries) GetConversationByIDAnyConv(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversationByIDAnyConv, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ParentID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.CreatedBy,
		&i.PositionKey,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConversationMember = `-- name: GetConversationMember :one
SELECT conversation_id, user_id, org_id, joined_at, last_read_at, muted FROM conversation_members WHERE conversation_id = ? AND user_id = ?
`

type GetConversationMemberParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) GetConversationMember(ctx context.Context, arg GetConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRowContext(ctx, getConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.OrgID,
		&i.JoinedAt,
		&i.LastReadAt,
		&i.Muted,
	)
	return i, err
}

const getLastMessage = `-- name: GetLastMessage :one
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content,
       m.parent_id, m.forwarded_message_id,
       m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at
FROM messages m
WHERE m.conversation_id = ? AND m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT 1
`

func (q *Queries) GetLastMessage(ctx context.Context, conversationID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getLastMessage, conversationID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderID,
		&i.Content,
		&i.SearchContent,
		&i.ParentID,
		&i.ForwardedMessageID,
		&i.Pinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectChannelLinks = `-- name: GetProjectChannelLinks :many
SELECT channel_id FROM channel_project_links WHERE project_id = ?
`

func (q *Queries) GetProjectChannelLinks(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProjectChannelLinks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var channel_id string
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCounts = `-- name: GetUnreadCounts :many
SELECT m.conversation_id, COUNT(*) AS unread
FROM messages m
INNER JOIN conversation_members cm ON cm.conversation_id = m.conversation_id AND cm.user_id = ?1
WHERE m.conversation_id IN (/*SLICE:conversation_ids*/?)
  AND m.deleted_at IS NULL
  AND m.created_at > cm.last_read_at
  AND m.sender_id != ?1
GROUP BY m.conversation_id
`

type GetUnreadCountsParams struct {
	UserID          string
	ConversationIds []string
}

type GetUnreadCountsRow struct {
	ConversationID string
	Unread         int64
}

func (q *Queries) GetUnreadCounts(ctx context.Context, arg GetUnreadCountsParams) ([]GetUnreadCountsRow, error) {
	query := getUnreadCounts
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.ConversationIds) > 0 {
		for _, v := range arg.ConversationIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", strings.Repeat(",?", len(arg.ConversationIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadCountsRow
	for rows.Next() {
		var i GetUnreadCountsRow
		if err := rows.Scan(&i.ConversationID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*) FROM messages m
INNER JOIN conversation_members cm ON cm.conversation_id = m.conversation_id AND cm.user_id = ?1
WHERE m.conversation_id = ?2
  AND m.deleted_at IS NULL
  AND m.created_at > cm.last_read_at
  AND m.sender_id != ?1
`

type GetUnreadMessageCountParams struct {
	UserID         string
	ConversationID string
}

func (q *Queries) GetUnreadMessageCount(ctx context.Context, arg GetUnreadMessageCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadMessageCount, arg.UserID, arg.ConversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersWithProjectAccess = `-- name: GetUsersWithProjectAccess :many
SELECT DISTINCT u.id, u.name, u.email, u.avatar_url, u.role
FROM users u
WHERE u.org_id = ?1 AND (
    u.role IN ('owner', 'admin', 'member')
    OR EXISTS (
        SELECT 1 FROM project_members pm
        WHERE pm.project_id = ?2 AND pm.user_id = u.id
    )
)
ORDER BY u.name
`

type GetUsersWithProjectAccessParams struct {
	OrgID     string
	ProjectID string
}

type GetUsersWithProjectAccessRow struct {
	ID        string
	Name      string
	Email     string
	AvatarUrl *string
	Role      string
}

func (q *Queries) GetUsersWithProjectAccess(ctx context.Context, arg GetUsersWithProjectAccessParams) ([]GetUsersWithProjectAccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersWithProjectAccess, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithProjectAccessRow
	for rows.Next() {
		var i GetUsersWithProjectAccessRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesByOrg = `-- name: ListCategoriesByOrg :many
SELECT id, org_id, parent_id, name, topic, type, created_by, position_key, deleted_at, created_at, updated_at FROM conversations
WHERE org_id = ?1
  AND type = 'category'
  AND deleted_at IS NULL
ORDER BY position_key ASC, id ASC
`

func (q *Queries) ListCategoriesByOrg(ctx context.Context, orgID string) ([]Conversation, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.CreatedBy,
			&i.PositionKey,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildPositionKeys = `-- name: ListChildPositionKeys :many
SELECT position_key FROM conversations
WHERE org_id = ?1
  AND parent_id = ?2
  AND type IN ('channel', 'voice')
  AND deleted_at IS NULL
ORDER BY position_key ASC
`

type ListChildPositionKeysParams struct {
	OrgID    string
	ParentID *string
}

func (q *Queries) ListChildPositionKeys(ctx context.Context, arg ListChildPositionKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listChildPositionKeys, arg.OrgID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var position_key string
		if err := rows.Scan(&position_key); err != nil {
			return nil, err
		}
		items = append(items, position_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT cm.conversation_id, cm.user_id, cm.org_id, cm.joined_at, cm.last_read_at, cm.muted, u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url, u.role AS user_role
FROM conversation_members cm
INNER JOIN users u ON u.id = cm.user_id
INNER JOIN conversations c ON c.id = cm.conversation_id AND c.org_id = cm.org_id
WHERE cm.conversation_id = ?
ORDER BY u.name ASC
`

type ListConversationMembersRow struct {
	ConversationID string
	UserID         string
	OrgID          string
	JoinedAt       string
	LastReadAt     string
	Muted          int64
	UserName       string
	UserEmail      string
	UserAvatarUrl  *string
	UserRole       string
}

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID string) ([]ListConversationMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationMembersRow
	for rows.Next() {
		var i ListConversationMembersRow
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.OrgID,
			&i.JoinedAt,
			&i.LastReadAt,
			&i.Muted,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByIDs = `-- name: ListConversationsByIDs :many
SELECT id, org_id, parent_id, name, topic, type, created_by, position_key, deleted_at, created_at, updated_at FROM conversations
WHERE org_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type ListConversationsByIDsParams struct {
	OrgID string
	Ids   []string
}

func (q *Queries) ListConversationsByIDs(ctx context.Context, arg ListConversationsByIDsParams) ([]Conversation, error) {
	query := listConversationsByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrgID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conversation
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.CreatedBy,
			&i.PositionKey,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByParent = `-- name: ListConversationsByParent :many
WITH RECURSIVE conv_with_link AS (
  -- anchor: conversations that directly have a project link
  SELECT c.id AS conv_id
  FROM conversations c
  WHERE EXISTS (SELECT 1 FROM channel_project_links cpl WHERE cpl.channel_id = c.id)
    AND c.org_id = ?1 AND c.deleted_at IS NULL
  UNION ALL
  -- recurse: children of linked conversations (descendants inherit access)
  SELECT c.id
  FROM conversations c
  JOIN conv_with_link p ON c.parent_id = p.conv_id
  WHERE c.org_id = ?1 AND c.deleted_at IS NULL
)
SELECT c.id, c.org_id, c.parent_id, c.name, c.topic, c.type, c.created_by, c.position_key, c.created_at, c.updated_at, c.deleted_at,
       (SELECT COUNT(*) FROM conversation_members WHERE conversation_id = c.id) AS member_count
FROM conversations c
WHERE c.org_id = ?1
  AND c.parent_id = ?2
  AND c.type IN ('channel', 'voice')
  AND c.deleted_at IS NULL
  AND (
    -- explicit membership
    EXISTS (SELECT 1 FROM conversation_members cm WHERE cm.conversation_id = c.id AND cm.user_id = ?3)
    OR (?4 = 1 AND c.id IN (SELECT conv_id FROM conv_with_link))
  )
ORDER BY c.position_key ASC, c.id ASC
`

type ListConversationsByParentParams struct {
	OrgID                string
	ParentID             *string
	UserID               string
	IncludeProjectLinked interface{}
}

type ListConversationsByParentRow struct {
	ID          string
	OrgID       string
	ParentID    *string
	Name        string
	Topic       string
	Type        string
	CreatedBy   string
	PositionKey string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   *string
	MemberCount int64
}

func (q *Queries) ListConversationsByParent(ctx context.Context, arg ListConversationsByParentParams) ([]ListConversationsByParentRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByParent,
		arg.OrgID,
		arg.ParentID,
		arg.UserID,
		arg.IncludeProjectLinked,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByParentRow
	for rows.Next() {
		var i ListConversationsByParentRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.CreatedBy,
			&i.PositionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsByUser = `-- name: ListConversationsByUser :many
WITH RECURSIVE conv_with_link AS (
  -- anchor: conversations that directly have a project link
  SELECT c.id AS conv_id
  FROM conversations c
  WHERE EXISTS (SELECT 1 FROM channel_project_links cpl WHERE cpl.channel_id = c.id)
    AND c.org_id = ?1 AND c.deleted_at IS NULL
  UNION ALL
  -- recurse: children of linked conversations (descendants inherit access)
  SELECT c.id
  FROM conversations c
  JOIN conv_with_link p ON c.parent_id = p.conv_id
  WHERE c.org_id = ?1 AND c.deleted_at IS NULL
)
SELECT c.id, c.org_id, c.parent_id, c.name, c.topic, c.type, c.created_by, c.position_key, c.created_at, c.updated_at, c.deleted_at,
       (SELECT COUNT(*) FROM conversation_members WHERE conversation_id = c.id) AS member_count
FROM conversations c
WHERE c.org_id = ?1
  AND c.deleted_at IS NULL
  AND (
    -- explicit membership
    EXISTS (SELECT 1 FROM conversation_members cm WHERE cm.conversation_id = c.id AND cm.user_id = ?2)
    OR (?3 = 1 AND c.id IN (SELECT conv_id FROM conv_with_link))
  )
  AND (
    ?4 = ''
    OR (?4 = 'workspace' AND c.type IN ('channel', 'voice', 'category'))
    OR (?4 = 'dms' AND c.type IN ('direct', 'group'))
    OR (substr(?4, 1, 8) = 'parent:' AND c.parent_id = substr(?4, 9))
  )
  AND (
    ?5 = ''
    OR c.position_key > ?5
    OR (c.position_key = ?5 AND c.id > ?6)
  )
ORDER BY c.position_key ASC, c.id ASC
LIMIT ?7
`

type ListConversationsByUserParams struct {
	OrgID                string
	UserID               string
	IncludeProjectLinked interface{}
	Scope                interface{}
	CursorKey            interface{}
	CursorID             string
	LimitVal             int64
}

type ListConversationsByUserRow struct {
	ID          string
	OrgID       string
	ParentID    *string
	Name        string
	Topic       string
	Type        string
	CreatedBy   string
	PositionKey string
	CreatedAt   string
	UpdatedAt   string
	DeletedAt   *string
	MemberCount int64
}

func (q *Queries) ListConversationsByUser(ctx context.Context, arg ListConversationsByUserParams) ([]ListConversationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversationsByUser,
		arg.OrgID,
		arg.UserID,
		arg.IncludeProjectLinked,
		arg.Scope,
		arg.CursorKey,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByUserRow
	for rows.Next() {
		var i ListConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ParentID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.CreatedBy,
			&i.PositionKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedMessages = `-- name: ListPinnedMessages :many
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content,
       m.parent_id, m.forwarded_message_id,
       m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at,
       u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = ? AND m.pinned = 1 AND m.deleted_at IS NULL
ORDER BY m.pinned_at DESC
`

type ListPinnedMessagesRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) ListPinnedMessages(ctx context.Context, conversationID string) ([]ListPinnedMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPinnedMessagesRow
	for rows.Next() {
		var i ListPinnedMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderID,
			&i.Content,
			&i.SearchContent,
			&i.ParentID,
			&i.ForwardedMessageID,
			&i.Pinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeConversationMember = `-- name: RemoveConversationMember :exec
DELETE FROM conversation_members WHERE conversation_id = ? AND user_id = ?
`

type RemoveConversationMemberParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) RemoveConversationMember(ctx context.Context, arg RemoveConversationMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const updateConversation = `-- name: UpdateConversation :exec
UPDATE conversations SET name = ?, topic = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateConversationParams struct {
	Name  string
	Topic string
	ID    string
	OrgID string
}

func (q *Queries) UpdateConversation(ctx context.Context, arg UpdateConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateConversation,
		arg.Name,
		arg.Topic,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateConversationParent = `-- name: UpdateConversationParent :exec
UPDATE conversations SET parent_id = ?, position_key = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateConversationParentParams struct {
	ParentID    *string
	PositionKey string
	ID          string
	OrgID       string
}

func (q *Queries) UpdateConversationParent(ctx context.Context, arg UpdateConversationParentParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationParent,
		arg.ParentID,
		arg.PositionKey,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateConversationPositionKey = `-- name: UpdateConversationPositionKey :exec
UPDATE conversations SET position_key = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateConversationPositionKeyParams struct {
	PositionKey string
	ID          string
	OrgID       string
}

func (q *Queries) UpdateConversationPositionKey(ctx context.Context, arg UpdateConversationPositionKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateConversationPositionKey, arg.PositionKey, arg.ID, arg.OrgID)
	return err
}

const updateLastRead = `-- name: UpdateLastRead :exec
UPDATE conversation_members SET last_read_at = datetime('now')
WHERE conversation_id = ? AND user_id = ?
`

type UpdateLastReadParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.ExecContext(ctx, updateLastRead, arg.ConversationID, arg.UserID)
	return err
}

const userHasProjectAccess = `-- name: UserHasProjectAccess :one
SELECT EXISTS (
    SELECT 1 FROM projects p
    WHERE p.id = ?1 AND p.org_id = ?2
    AND (
        @user_role IN ('owner', 'admin', 'member')
        OR EXISTS (
            SELECT 1 FROM project_members pm
            WHERE pm.project_id = p.id AND pm.user_id = ?3
        )
    )
) AS has_access
`

type UserHasProjectAccessParams struct {
	ProjectID string
	OrgID     string
	UserID    string
}

func (q *Queries) UserHasProjectAccess(ctx context.Context, arg UserHasProjectAccessParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasProjectAccess, arg.ProjectID, arg.OrgID, arg.UserID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}
