// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_fields.sql

package sqlc

import (
	"context"
	"strings"
)

const createCustomField = `-- name: CreateCustomField :exec
INSERT INTO custom_fields (id, org_id, project_id, name, field_type, options, position)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateCustomFieldParams struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	FieldType string
	Options   string
	Position  int64
}

func (q *Queries) CreateCustomField(ctx context.Context, arg CreateCustomFieldParams) error {
	_, err := q.db.ExecContext(ctx, createCustomField,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.FieldType,
		arg.Options,
		arg.Position,
	)
	return err
}

const deleteCustomField = `-- name: DeleteCustomField :exec
DELETE FROM custom_fields WHERE id = ? AND org_id = ?
`

type DeleteCustomFieldParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteCustomField(ctx context.Context, arg DeleteCustomFieldParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomField, arg.ID, arg.OrgID)
	return err
}

const deleteTaskCustomFieldValues = `-- name: DeleteTaskCustomFieldValues :exec
DELETE FROM task_custom_field_values WHERE task_id = ?
`

func (q *Queries) DeleteTaskCustomFieldValues(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, deleteTaskCustomFieldValues, taskID)
	return err
}

const getCustomFieldByID = `-- name: GetCustomFieldByID :one
SELECT id, org_id, project_id, name, field_type, options, position, created_at, updated_at
FROM custom_fields
WHERE id = ? AND org_id = ?
`

type GetCustomFieldByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetCustomFieldByID(ctx context.Context, arg GetCustomFieldByIDParams) (CustomField, error) {
	row := q.db.QueryRowContext(ctx, getCustomFieldByID, arg.ID, arg.OrgID)
	var i CustomField
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.FieldType,
		&i.Options,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskCustomFieldValues = `-- name: GetTaskCustomFieldValues :many
SELECT task_id, custom_field_id, value, updated_at
FROM task_custom_field_values
WHERE task_id = ?
`

func (q *Queries) GetTaskCustomFieldValues(ctx context.Context, taskID string) ([]TaskCustomFieldValue, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCustomFieldValues, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCustomFieldValue
	for rows.Next() {
		var i TaskCustomFieldValue
		if err := rows.Scan(
			&i.TaskID,
			&i.CustomFieldID,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldsByProject = `-- name: ListCustomFieldsByProject :many
SELECT id, org_id, project_id, name, field_type, options, position, created_at, updated_at
FROM custom_fields
WHERE project_id = ? AND org_id = ?
ORDER BY position ASC
`

type ListCustomFieldsByProjectParams struct {
	ProjectID string
	OrgID     string
}

func (q *Queries) ListCustomFieldsByProject(ctx context.Context, arg ListCustomFieldsByProjectParams) ([]CustomField, error) {
	rows, err := q.db.QueryContext(ctx, listCustomFieldsByProject, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CustomField
	for rows.Next() {
		var i CustomField
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.FieldType,
			&i.Options,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCustomFieldValuesByTaskIDs = `-- name: ListTaskCustomFieldValuesByTaskIDs :many
SELECT task_id, custom_field_id, value, updated_at
FROM task_custom_field_values
WHERE task_id IN (/*SLICE:task_ids*/?)
`

func (q *Queries) ListTaskCustomFieldValuesByTaskIDs(ctx context.Context, taskIds []string) ([]TaskCustomFieldValue, error) {
	query := listTaskCustomFieldValuesByTaskIDs
	var queryParams []interface{}
	if len(taskIds) > 0 {
		for _, v := range taskIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:task_ids*/?", strings.Repeat(",?", len(taskIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:task_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskCustomFieldValue
	for rows.Next() {
		var i TaskCustomFieldValue
		if err := rows.Scan(
			&i.TaskID,
			&i.CustomFieldID,
			&i.Value,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskCustomFieldValue = `-- name: SetTaskCustomFieldValue :exec
INSERT INTO task_custom_field_values (task_id, custom_field_id, value, updated_at)
VALUES (?, ?, ?, datetime('now'))
ON CONFLICT(task_id, custom_field_id) DO UPDATE SET value = excluded.value, updated_at = datetime('now')
`

type SetTaskCustomFieldValueParams struct {
	TaskID        string
	CustomFieldID string
	Value         string
}

func (q *Queries) SetTaskCustomFieldValue(ctx context.Context, arg SetTaskCustomFieldValueParams) error {
	_, err := q.db.ExecContext(ctx, setTaskCustomFieldValue, arg.TaskID, arg.CustomFieldID, arg.Value)
	return err
}

const updateCustomField = `-- name: UpdateCustomField :exec
UPDATE custom_fields
SET name = ?, options = ?, position = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateCustomFieldParams struct {
	Name     string
	Options  string
	Position int64
	ID       string
	OrgID    string
}

func (q *Queries) UpdateCustomField(ctx context.Context, arg UpdateCustomFieldParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomField,
		arg.Name,
		arg.Options,
		arg.Position,
		arg.ID,
		arg.OrgID,
	)
	return err
}
