// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cycles.sql

package sqlc

import (
	"context"
)

const countCyclesByProject = `-- name: CountCyclesByProject :one
SELECT COUNT(*) FROM cycles WHERE project_id = ?1
`

func (q *Queries) CountCyclesByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCyclesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByCycle = `-- name: CountTasksByCycle :one
SELECT
  COUNT(*) AS total,
  SUM(CASE WHEN completed_at IS NOT NULL THEN 1 ELSE 0 END) AS completed
FROM tasks
WHERE cycle_id = ?1
`

type CountTasksByCycleRow struct {
	Total     int64
	Completed *float64
}

func (q *Queries) CountTasksByCycle(ctx context.Context, cycleID *string) (CountTasksByCycleRow, error) {
	row := q.db.QueryRowContext(ctx, countTasksByCycle, cycleID)
	var i CountTasksByCycleRow
	err := row.Scan(&i.Total, &i.Completed)
	return i, err
}

const countTasksByCycles = `-- name: CountTasksByCycles :many
SELECT
  c.id AS cycle_id,
  COUNT(t.id) AS total,
  SUM(CASE WHEN t.completed_at IS NOT NULL THEN 1 ELSE 0 END) AS completed
FROM cycles c
LEFT JOIN tasks t ON t.cycle_id = c.id
WHERE c.project_id = ?1
GROUP BY c.id
`

type CountTasksByCyclesRow struct {
	CycleID   string
	Total     int64
	Completed *float64
}

func (q *Queries) CountTasksByCycles(ctx context.Context, projectID string) ([]CountTasksByCyclesRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByCycles, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByCyclesRow
	for rows.Next() {
		var i CountTasksByCyclesRow
		if err := rows.Scan(&i.CycleID, &i.Total, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCycle = `-- name: CreateCycle :exec
INSERT INTO cycles (id, org_id, project_id, name, goal, starts_at, ends_at, created_by)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
`

type CreateCycleParams struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	Goal      string
	StartsAt  string
	EndsAt    string
	CreatedBy string
}

func (q *Queries) CreateCycle(ctx context.Context, arg CreateCycleParams) error {
	_, err := q.db.ExecContext(ctx, createCycle,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.Goal,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	return err
}

const deactivateAllCycles = `-- name: DeactivateAllCycles :exec
UPDATE cycles SET is_active = FALSE, updated_at = datetime('now') WHERE project_id = ?1
`

func (q *Queries) DeactivateAllCycles(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deactivateAllCycles, projectID)
	return err
}

const deleteCycle = `-- name: DeleteCycle :exec
DELETE FROM cycles
WHERE id = ?1 AND project_id = ?2
`

type DeleteCycleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteCycle(ctx context.Context, arg DeleteCycleParams) error {
	_, err := q.db.ExecContext(ctx, deleteCycle, arg.ID, arg.ProjectID)
	return err
}

const getActiveCycleByProject = `-- name: GetActiveCycleByProject :one
SELECT id, org_id, project_id, name, goal, starts_at, ends_at, created_by, is_completed, is_active, created_at, updated_at
FROM cycles
WHERE project_id = ?1 AND is_active = TRUE
`

func (q *Queries) GetActiveCycleByProject(ctx context.Context, projectID string) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getActiveCycleByProject, projectID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsCompleted,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCycleByID = `-- name: GetCycleByID :one
SELECT id, org_id, project_id, name, goal, starts_at, ends_at, created_by, is_completed, is_active, created_at, updated_at
FROM cycles
WHERE id = ?1 AND project_id = ?2
`

type GetCycleByIDParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetCycleByID(ctx context.Context, arg GetCycleByIDParams) (Cycle, error) {
	row := q.db.QueryRowContext(ctx, getCycleByID, arg.ID, arg.ProjectID)
	var i Cycle
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Goal,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.IsCompleted,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCyclesByProject = `-- name: ListCyclesByProject :many
SELECT id, org_id, project_id, name, goal, starts_at, ends_at, created_by, is_completed, is_active, created_at, updated_at
FROM cycles
WHERE project_id = ?1
ORDER BY starts_at ASC
`

func (q *Queries) ListCyclesByProject(ctx context.Context, projectID string) ([]Cycle, error) {
	rows, err := q.db.QueryContext(ctx, listCyclesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cycle
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Goal,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.IsCompleted,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCycleActive = `-- name: SetCycleActive :exec
UPDATE cycles SET is_active = TRUE, updated_at = datetime('now') WHERE id = ?1 AND project_id = ?2
`

type SetCycleActiveParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) SetCycleActive(ctx context.Context, arg SetCycleActiveParams) error {
	_, err := q.db.ExecContext(ctx, setCycleActive, arg.ID, arg.ProjectID)
	return err
}

const updateCycle = `-- name: UpdateCycle :exec
UPDATE cycles
SET name = ?1, goal = ?2, starts_at = ?3, ends_at = ?4, is_completed = ?5, is_active = ?6, updated_at = datetime('now')
WHERE id = ?7 AND project_id = ?8
`

type UpdateCycleParams struct {
	Name        string
	Goal        string
	StartsAt    string
	EndsAt      string
	IsCompleted bool
	IsActive    bool
	ID          string
	ProjectID   string
}

func (q *Queries) UpdateCycle(ctx context.Context, arg UpdateCycleParams) error {
	_, err := q.db.ExecContext(ctx, updateCycle,
		arg.Name,
		arg.Goal,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsCompleted,
		arg.IsActive,
		arg.ID,
		arg.ProjectID,
	)
	return err
}
