// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package sqlc

import (
	"context"
)

const dueSoonTasks = `-- name: DueSoonTasks :many
SELECT t.id, t.title, t.priority, t.status_id, ts.name AS status_name, ts.color AS status_color,
       t.project_id, p.name AS project_name, p.slug AS project_slug, t.due_at
FROM tasks t
JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
JOIN projects p ON p.id = t.project_id AND p.org_id = ?2
JOIN task_statuses ts ON ts.id = t.status_id
WHERE t.org_id = ?2
  AND t.due_at IS NOT NULL
  AND t.completed_at IS NULL
ORDER BY t.due_at ASC
LIMIT ?3
`

type DueSoonTasksParams struct {
	UserID string
	OrgID  string
	Limit  int64
}

type DueSoonTasksRow struct {
	ID          string
	Title       string
	Priority    string
	StatusID    string
	StatusName  string
	StatusColor string
	ProjectID   string
	ProjectName string
	ProjectSlug string
	DueAt       *string
}

func (q *Queries) DueSoonTasks(ctx context.Context, arg DueSoonTasksParams) ([]DueSoonTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, dueSoonTasks, arg.UserID, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueSoonTasksRow
	for rows.Next() {
		var i DueSoonTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.StatusID,
			&i.StatusName,
			&i.StatusColor,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardPreferences = `-- name: GetDashboardPreferences :one
SELECT sections FROM dashboard_preferences
WHERE user_id = ?1 AND org_id = ?2
`

type GetDashboardPreferencesParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) GetDashboardPreferences(ctx context.Context, arg GetDashboardPreferencesParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getDashboardPreferences, arg.UserID, arg.OrgID)
	var sections string
	err := row.Scan(&sections)
	return sections, err
}

const myTaskStats = `-- name: MyTaskStats :one
SELECT
  (SELECT COUNT(*) FROM tasks t
   JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
   WHERE t.org_id = ?2 AND t.completed_at IS NULL) AS assigned_count,
  (SELECT COUNT(*) FROM tasks t
   JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
   WHERE t.org_id = ?2 AND t.due_at IS NOT NULL AND t.due_at < datetime('now') AND t.completed_at IS NULL) AS overdue_count,
  (SELECT COUNT(*) FROM tasks t
   JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
   WHERE t.org_id = ?2 AND t.due_at IS NOT NULL AND t.due_at >= datetime('now') AND t.due_at < datetime('now', '+7 days') AND t.completed_at IS NULL) AS due_this_week_count,
  (SELECT COUNT(*) FROM tasks t
   JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
   WHERE t.org_id = ?2 AND t.completed_at IS NOT NULL) AS completed_count,
  (SELECT COUNT(*) FROM projects WHERE org_id = ?2) AS total_projects
`

type MyTaskStatsParams struct {
	UserID string
	OrgID  string
}

type MyTaskStatsRow struct {
	AssignedCount    int64
	OverdueCount     int64
	DueThisWeekCount int64
	CompletedCount   int64
	TotalProjects    int64
}

func (q *Queries) MyTaskStats(ctx context.Context, arg MyTaskStatsParams) (MyTaskStatsRow, error) {
	row := q.db.QueryRowContext(ctx, myTaskStats, arg.UserID, arg.OrgID)
	var i MyTaskStatsRow
	err := row.Scan(
		&i.AssignedCount,
		&i.OverdueCount,
		&i.DueThisWeekCount,
		&i.CompletedCount,
		&i.TotalProjects,
	)
	return i, err
}

const myTasks = `-- name: MyTasks :many
SELECT t.id, t.title, t.priority, t.status_id, ts.name AS status_name, ts.color AS status_color,
       t.project_id, p.name AS project_name, p.slug AS project_slug, t.due_at
FROM tasks t
JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
JOIN projects p ON p.id = t.project_id AND p.org_id = ?2
JOIN task_statuses ts ON ts.id = t.status_id
WHERE t.org_id = ?2
  AND t.completed_at IS NULL
ORDER BY CASE WHEN t.priority = 'urgent' THEN 0 WHEN t.priority = 'high' THEN 1 WHEN t.priority = 'medium' THEN 2 ELSE 3 END,
         t.due_at ASC NULLS LAST,
         t.updated_at DESC
LIMIT ?3
`

type MyTasksParams struct {
	UserID string
	OrgID  string
	Limit  int64
}

type MyTasksRow struct {
	ID          string
	Title       string
	Priority    string
	StatusID    string
	StatusName  string
	StatusColor string
	ProjectID   string
	ProjectName string
	ProjectSlug string
	DueAt       *string
}

func (q *Queries) MyTasks(ctx context.Context, arg MyTasksParams) ([]MyTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, myTasks, arg.UserID, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MyTasksRow
	for rows.Next() {
		var i MyTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Priority,
			&i.StatusID,
			&i.StatusName,
			&i.StatusColor,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgProjects = `-- name: OrgProjects :many
SELECT p.id, p.name, p.slug, p.color, p.icon,
       (SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id AND t.completed_at IS NULL) AS task_count,
       (SELECT COUNT(*) FROM project_members pm WHERE pm.project_id = p.id) AS member_count
FROM projects p
WHERE p.org_id = ?1
ORDER BY p.updated_at DESC
`

type OrgProjectsRow struct {
	ID          string
	Name        string
	Slug        string
	Color       string
	Icon        string
	TaskCount   int64
	MemberCount int64
}

func (q *Queries) OrgProjects(ctx context.Context, orgID string) ([]OrgProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, orgProjects, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgProjectsRow
	for rows.Next() {
		var i OrgProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.Icon,
			&i.TaskCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orgProjectsForUser = `-- name: OrgProjectsForUser :many
SELECT p.id, p.name, p.slug, p.color, p.icon,
       (SELECT COUNT(*) FROM tasks t WHERE t.project_id = p.id AND t.completed_at IS NULL) AS task_count,
       (SELECT COUNT(*) FROM project_members pm2 WHERE pm2.project_id = p.id) AS member_count
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?1
WHERE p.org_id = ?2
ORDER BY p.updated_at DESC
`

type OrgProjectsForUserParams struct {
	UserID string
	OrgID  string
}

type OrgProjectsForUserRow struct {
	ID          string
	Name        string
	Slug        string
	Color       string
	Icon        string
	TaskCount   int64
	MemberCount int64
}

// Projects the caller is an explicit member of. Used for the dashboard
// "projects" section when the caller is a viewer/guest (project-scoped role).
func (q *Queries) OrgProjectsForUser(ctx context.Context, arg OrgProjectsForUserParams) ([]OrgProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, orgProjectsForUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgProjectsForUserRow
	for rows.Next() {
		var i OrgProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.Icon,
			&i.TaskCount,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentActivity = `-- name: RecentActivity :many
SELECT n.id, n.type, n.title, n.body, n.link,
       n.entity_type, n.entity_id, n.is_read, n.created_at,
       COALESCE(u.name, '') AS actor_name,
       COALESCE(p.slug, '') AS project_slug
FROM notifications n
LEFT JOIN users u ON u.id = n.actor_id
LEFT JOIN tasks t ON t.id = n.entity_id AND n.entity_type = 'task'
LEFT JOIN projects p ON p.id = t.project_id
WHERE n.user_id = ?1 AND n.org_id = ?2
ORDER BY n.created_at DESC
LIMIT ?3
`

type RecentActivityParams struct {
	UserID string
	OrgID  string
	Limit  int64
}

type RecentActivityRow struct {
	ID          string
	Type        string
	Title       string
	Body        string
	Link        string
	EntityType  string
	EntityID    string
	IsRead      int64
	CreatedAt   string
	ActorName   string
	ProjectSlug string
}

func (q *Queries) RecentActivity(ctx context.Context, arg RecentActivityParams) ([]RecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, recentActivity, arg.UserID, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentActivityRow
	for rows.Next() {
		var i RecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.EntityType,
			&i.EntityID,
			&i.IsRead,
			&i.CreatedAt,
			&i.ActorName,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDashboardPreferences = `-- name: SetDashboardPreferences :exec
INSERT INTO dashboard_preferences (user_id, org_id, sections)
VALUES (?1, ?2, ?3)
ON CONFLICT(user_id, org_id) DO UPDATE SET sections = excluded.sections
`

type SetDashboardPreferencesParams struct {
	UserID   string
	OrgID    string
	Sections string
}

func (q *Queries) SetDashboardPreferences(ctx context.Context, arg SetDashboardPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, setDashboardPreferences, arg.UserID, arg.OrgID, arg.Sections)
	return err
}
