// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package sqlc

import (
	"context"
)

const createUserInvite = `-- name: CreateUserInvite :exec
INSERT INTO user_invites (id, org_id, email, role, token_hash, invited_by, max_uses, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserInviteParams struct {
	ID        string
	OrgID     string
	Email     *string
	Role      string
	TokenHash string
	InvitedBy string
	MaxUses   *int64
	ExpiresAt string
}

func (q *Queries) CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) error {
	_, err := q.db.ExecContext(ctx, createUserInvite,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	return err
}

const deleteUserInvite = `-- name: DeleteUserInvite :exec
DELETE FROM user_invites WHERE id = ? AND org_id = ?
`

type DeleteUserInviteParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteUserInvite(ctx context.Context, arg DeleteUserInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserInvite, arg.ID, arg.OrgID)
	return err
}

const getUserInviteByTokenHash = `-- name: GetUserInviteByTokenHash :one
SELECT id, org_id, email, role, token_hash, invited_by, max_uses, use_count, expires_at, created_at
FROM user_invites
WHERE token_hash = ? AND expires_at > datetime('now')
  AND (max_uses IS NULL OR use_count < max_uses)
`

func (q *Queries) GetUserInviteByTokenHash(ctx context.Context, tokenHash string) (UserInvite, error) {
	row := q.db.QueryRowContext(ctx, getUserInviteByTokenHash, tokenHash)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.MaxUses,
		&i.UseCount,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteUseCount = `-- name: IncrementInviteUseCount :exec
UPDATE user_invites SET use_count = use_count + 1 WHERE id = ?
`

func (q *Queries) IncrementInviteUseCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementInviteUseCount, id)
	return err
}

const listUserInvites = `-- name: ListUserInvites :many
SELECT i.id, i.org_id, i.email, i.role, i.invited_by, i.use_count, i.expires_at, i.created_at,
       u.name as invited_by_name
FROM user_invites i
JOIN users u ON u.id = i.invited_by
WHERE i.org_id = ?1
ORDER BY i.created_at DESC
LIMIT ?2
`

type ListUserInvitesParams struct {
	OrgID    string
	LimitVal int64
}

type ListUserInvitesRow struct {
	ID            string
	OrgID         string
	Email         *string
	Role          string
	InvitedBy     string
	UseCount      int64
	ExpiresAt     string
	CreatedAt     string
	InvitedByName string
}

func (q *Queries) ListUserInvites(ctx context.Context, arg ListUserInvitesParams) ([]ListUserInvitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserInvites, arg.OrgID, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserInvitesRow
	for rows.Next() {
		var i ListUserInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.UseCount,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.InvitedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordInviteAcceptance = `-- name: RecordInviteAcceptance :exec
INSERT INTO user_invite_acceptances (id, invite_id, user_id)
VALUES (?, ?, ?)
`

type RecordInviteAcceptanceParams struct {
	ID       string
	InviteID string
	UserID   string
}

func (q *Queries) RecordInviteAcceptance(ctx context.Context, arg RecordInviteAcceptanceParams) error {
	_, err := q.db.ExecContext(ctx, recordInviteAcceptance, arg.ID, arg.InviteID, arg.UserID)
	return err
}
