// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite_projects.sql

package sqlc

import (
	"context"
)

const addInviteProject = `-- name: AddInviteProject :exec
INSERT INTO invite_projects (invite_id, project_id, role)
VALUES (?, ?, ?)
`

type AddInviteProjectParams struct {
	InviteID  string
	ProjectID string
	Role      string
}

func (q *Queries) AddInviteProject(ctx context.Context, arg AddInviteProjectParams) error {
	_, err := q.db.ExecContext(ctx, addInviteProject, arg.InviteID, arg.ProjectID, arg.Role)
	return err
}

const deleteInviteProjects = `-- name: DeleteInviteProjects :exec
DELETE FROM invite_projects
WHERE invite_id = ?
`

func (q *Queries) DeleteInviteProjects(ctx context.Context, inviteID string) error {
	_, err := q.db.ExecContext(ctx, deleteInviteProjects, inviteID)
	return err
}

const listInviteProjects = `-- name: ListInviteProjects :many
SELECT project_id, role
FROM invite_projects
WHERE invite_id = ?
`

type ListInviteProjectsRow struct {
	ProjectID string
	Role      string
}

func (q *Queries) ListInviteProjects(ctx context.Context, inviteID string) ([]ListInviteProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInviteProjects, inviteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInviteProjectsRow
	for rows.Next() {
		var i ListInviteProjectsRow
		if err := rows.Scan(&i.ProjectID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
