// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"
	"strings"
)

const addTaskLabel = `-- name: AddTaskLabel :exec
INSERT INTO task_labels (task_id, label_id)
VALUES (?, ?)
`

type AddTaskLabelParams struct {
	TaskID  string
	LabelID string
}

func (q *Queries) AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error {
	_, err := q.db.ExecContext(ctx, addTaskLabel, arg.TaskID, arg.LabelID)
	return err
}

const clearTaskLabels = `-- name: ClearTaskLabels :exec
DELETE FROM task_labels WHERE task_id = ?
`

func (q *Queries) ClearTaskLabels(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, clearTaskLabels, taskID)
	return err
}

const createLabel = `-- name: CreateLabel :exec
INSERT INTO labels (id, org_id, name, color)
VALUES (?, ?, ?, ?)
`

type CreateLabelParams struct {
	ID    string
	OrgID string
	Name  string
	Color string
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) error {
	_, err := q.db.ExecContext(ctx, createLabel,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Color,
	)
	return err
}

const deleteLabel = `-- name: DeleteLabel :exec
DELETE FROM labels WHERE id = ? AND org_id = ?
`

type DeleteLabelParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteLabel(ctx context.Context, arg DeleteLabelParams) error {
	_, err := q.db.ExecContext(ctx, deleteLabel, arg.ID, arg.OrgID)
	return err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT id, org_id, name, color, created_at, updated_at
FROM labels
WHERE id = ? AND org_id = ?
`

type GetLabelByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetLabelByID(ctx context.Context, arg GetLabelByIDParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, getLabelByID, arg.ID, arg.OrgID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskLabels = `-- name: GetTaskLabels :many
SELECT l.id, l.org_id, l.name, l.color, l.created_at, l.updated_at
FROM labels l
INNER JOIN task_labels tl ON tl.label_id = l.id
WHERE tl.task_id = ?
ORDER BY l.name ASC
`

func (q *Queries) GetTaskLabels(ctx context.Context, taskID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, getTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByOrg = `-- name: ListLabelsByOrg :many
SELECT id, org_id, name, color, created_at, updated_at
FROM labels
WHERE org_id = ?
ORDER BY name ASC
`

func (q *Queries) ListLabelsByOrg(ctx context.Context, orgID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, listLabelsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabelsByTaskIDs = `-- name: ListLabelsByTaskIDs :many
SELECT tl.task_id, l.id, l.org_id, l.name, l.color, l.created_at, l.updated_at
FROM task_labels tl
INNER JOIN labels l ON l.id = tl.label_id
WHERE tl.task_id IN (/*SLICE:task_ids*/?)
ORDER BY l.name ASC
`

type ListLabelsByTaskIDsRow struct {
	TaskID    string
	ID        string
	OrgID     string
	Name      string
	Color     string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) ListLabelsByTaskIDs(ctx context.Context, taskIds []string) ([]ListLabelsByTaskIDsRow, error) {
	query := listLabelsByTaskIDs
	var queryParams []interface{}
	if len(taskIds) > 0 {
		for _, v := range taskIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:task_ids*/?", strings.Repeat(",?", len(taskIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:task_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabelsByTaskIDsRow
	for rows.Next() {
		var i ListLabelsByTaskIDsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabel = `-- name: UpdateLabel :exec
UPDATE labels
SET name = ?, color = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateLabelParams struct {
	Name  string
	Color string
	ID    string
	OrgID string
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) error {
	_, err := q.db.ExecContext(ctx, updateLabel,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.OrgID,
	)
	return err
}
