// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mentions.sql

package sqlc

import (
	"context"
	"strings"
)

const getProjectsByIDs = `-- name: GetProjectsByIDs :many
SELECT id, name, org_id, icon, color
FROM projects
WHERE id IN (/*SLICE:ids*/?)
`

type GetProjectsByIDsRow struct {
	ID    string
	Name  string
	OrgID string
	Icon  string
	Color string
}

// Batch fetch projects by IDs for mention hydration.
func (q *Queries) GetProjectsByIDs(ctx context.Context, ids []string) ([]GetProjectsByIDsRow, error) {
	query := getProjectsByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsByIDsRow
	for rows.Next() {
		var i GetProjectsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByIDs = `-- name: GetTasksByIDs :many
SELECT id, title, project_id, org_id
FROM tasks
WHERE org_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type GetTasksByIDsParams struct {
	OrgID string
	Ids   []string
}

type GetTasksByIDsRow struct {
	ID        string
	Title     string
	ProjectID string
	OrgID     string
}

// Batch fetch tasks by IDs for mention hydration. Org-scoped so foreign-org
// IDs simply don't match (no Go post-filter needed).
func (q *Queries) GetTasksByIDs(ctx context.Context, arg GetTasksByIDsParams) ([]GetTasksByIDsRow, error) {
	query := getTasksByIDs
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrgID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTasksByIDsRow
	for rows.Next() {
		var i GetTasksByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.OrgID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionChannels = `-- name: SearchMentionChannels :many
SELECT c.id, c.name
FROM conversations c
INNER JOIN conversation_members cm ON cm.conversation_id = c.id AND cm.user_id = ?1
WHERE c.org_id = ?2
  AND c.type = 'channel'
  AND c.deleted_at IS NULL
  AND (?3 = '' OR instr(lower(c.name), lower(?3)) > 0)
ORDER BY c.name ASC
LIMIT ?4
`

type SearchMentionChannelsParams struct {
	UserID   string
	OrgID    string
	Query    interface{}
	LimitVal int64
}

type SearchMentionChannelsRow struct {
	ID   string
	Name string
}

// Search channels (type=channel) accessible to the requesting user.
func (q *Queries) SearchMentionChannels(ctx context.Context, arg SearchMentionChannelsParams) ([]SearchMentionChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionChannels,
		arg.UserID,
		arg.OrgID,
		arg.Query,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionChannelsRow
	for rows.Next() {
		var i SearchMentionChannelsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionProjects = `-- name: SearchMentionProjects :many
SELECT p.id, p.name, p.icon, p.color
FROM projects p
WHERE p.org_id = ?1
  AND (?2 = '' OR instr(lower(p.name), lower(?2)) > 0)
ORDER BY p.name ASC
LIMIT ?3
`

type SearchMentionProjectsParams struct {
	OrgID    string
	Query    interface{}
	LimitVal int64
}

type SearchMentionProjectsRow struct {
	ID    string
	Name  string
	Icon  string
	Color string
}

// Search projects accessible to the requesting user (for privileged roles: owner/admin/member).
func (q *Queries) SearchMentionProjects(ctx context.Context, arg SearchMentionProjectsParams) ([]SearchMentionProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionProjects, arg.OrgID, arg.Query, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionProjectsRow
	for rows.Next() {
		var i SearchMentionProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionProjectsForUser = `-- name: SearchMentionProjectsForUser :many
SELECT p.id, p.name, p.icon, p.color
FROM projects p
INNER JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?1
WHERE p.org_id = ?2
  AND (?3 = '' OR instr(lower(p.name), lower(?3)) > 0)
ORDER BY p.name ASC
LIMIT ?4
`

type SearchMentionProjectsForUserParams struct {
	UserID   string
	OrgID    string
	Query    interface{}
	LimitVal int64
}

type SearchMentionProjectsForUserRow struct {
	ID    string
	Name  string
	Icon  string
	Color string
}

// Search projects the user is explicitly a member of (for viewer role).
func (q *Queries) SearchMentionProjectsForUser(ctx context.Context, arg SearchMentionProjectsForUserParams) ([]SearchMentionProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionProjectsForUser,
		arg.UserID,
		arg.OrgID,
		arg.Query,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionProjectsForUserRow
	for rows.Next() {
		var i SearchMentionProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionTasks = `-- name: SearchMentionTasks :many
SELECT t.id, t.title, t.project_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
WHERE t.org_id = ?1
  AND (?2 = '' OR instr(lower(t.title), lower(?2)) > 0)
ORDER BY t.updated_at DESC
LIMIT ?3
`

type SearchMentionTasksParams struct {
	OrgID    string
	Query    interface{}
	LimitVal int64
}

type SearchMentionTasksRow struct {
	ID          string
	Title       string
	ProjectID   string
	ProjectName string
}

// Search tasks by title across all projects in org (for privileged roles: owner/admin/member).
func (q *Queries) SearchMentionTasks(ctx context.Context, arg SearchMentionTasksParams) ([]SearchMentionTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionTasks, arg.OrgID, arg.Query, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionTasksRow
	for rows.Next() {
		var i SearchMentionTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionTasksForUser = `-- name: SearchMentionTasksForUser :many
SELECT t.id, t.title, t.project_id, p.name AS project_name
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
INNER JOIN project_members pm ON pm.project_id = t.project_id AND pm.user_id = ?2
WHERE t.org_id = ?1
  AND (?3 = '' OR instr(lower(t.title), lower(?3)) > 0)
ORDER BY t.updated_at DESC
LIMIT ?4
`

type SearchMentionTasksForUserParams struct {
	OrgID    string
	UserID   string
	Query    interface{}
	LimitVal int64
}

type SearchMentionTasksForUserRow struct {
	ID          string
	Title       string
	ProjectID   string
	ProjectName string
}

// Search tasks in projects the user is a member of (for viewer role).
func (q *Queries) SearchMentionTasksForUser(ctx context.Context, arg SearchMentionTasksForUserParams) ([]SearchMentionTasksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionTasksForUser,
		arg.OrgID,
		arg.UserID,
		arg.Query,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionTasksForUserRow
	for rows.Next() {
		var i SearchMentionTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMentionUsers = `-- name: SearchMentionUsers :many
SELECT id, name, avatar_url
FROM users
WHERE org_id = ?1
  AND is_active = 1
  AND (?2 = '' OR instr(lower(name), lower(?2)) > 0)
ORDER BY name ASC
LIMIT ?3
`

type SearchMentionUsersParams struct {
	OrgID    string
	Query    interface{}
	LimitVal int64
}

type SearchMentionUsersRow struct {
	ID        string
	Name      string
	AvatarUrl *string
}

// Search users by name within an org. Used for @mention autocomplete.
func (q *Queries) SearchMentionUsers(ctx context.Context, arg SearchMentionUsersParams) ([]SearchMentionUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMentionUsers, arg.OrgID, arg.Query, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMentionUsersRow
	for rows.Next() {
		var i SearchMentionUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
