// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"
	"strings"
)

const addReaction = `-- name: AddReaction :exec
INSERT INTO message_reactions (message_id, user_id, org_id, emoji)
VALUES (?, ?, ?, ?)
ON CONFLICT(message_id, user_id, emoji) DO NOTHING
`

type AddReactionParams struct {
	MessageID string
	UserID    string
	OrgID     string
	Emoji     string
}

func (q *Queries) AddReaction(ctx context.Context, arg AddReactionParams) error {
	_, err := q.db.ExecContext(ctx, addReaction,
		arg.MessageID,
		arg.UserID,
		arg.OrgID,
		arg.Emoji,
	)
	return err
}

const countMessages = `-- name: CountMessages :one
SELECT COUNT(*) FROM messages WHERE conversation_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountMessages(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, org_id, sender_id, content, search_content, parent_id, forwarded_message_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, conversation_id, org_id, sender_id, content, search_content, parent_id, forwarded_message_id, pinned, pinned_at, pinned_by, edited_at, deleted_at, created_at
`

type CreateMessageParams struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.OrgID,
		arg.SenderID,
		arg.Content,
		arg.SearchContent,
		arg.ParentID,
		arg.ForwardedMessageID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderID,
		&i.Content,
		&i.SearchContent,
		&i.ParentID,
		&i.ForwardedMessageID,
		&i.Pinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMessageAttachment = `-- name: CreateMessageAttachment :exec
INSERT INTO message_attachments (id, message_id, file_name, file_size, content_type, storage_path)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateMessageAttachmentParams struct {
	ID          string
	MessageID   string
	FileName    string
	FileSize    int64
	ContentType string
	StoragePath string
}

func (q *Queries) CreateMessageAttachment(ctx context.Context, arg CreateMessageAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createMessageAttachment,
		arg.ID,
		arg.MessageID,
		arg.FileName,
		arg.FileSize,
		arg.ContentType,
		arg.StoragePath,
	)
	return err
}

const deleteMessageAttachment = `-- name: DeleteMessageAttachment :exec
DELETE FROM message_attachments WHERE id = ?
`

func (q *Queries) DeleteMessageAttachment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMessageAttachment, id)
	return err
}

const getConversationLastMessage = `-- name: GetConversationLastMessage :one
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content, m.parent_id, m.forwarded_message_id, m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at, u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = ? AND m.deleted_at IS NULL
ORDER BY m.created_at DESC, m.id DESC
LIMIT 1
`

type GetConversationLastMessageRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) GetConversationLastMessage(ctx context.Context, conversationID string) (GetConversationLastMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationLastMessage, conversationID)
	var i GetConversationLastMessageRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderID,
		&i.Content,
		&i.SearchContent,
		&i.ParentID,
		&i.ForwardedMessageID,
		&i.Pinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderAvatarUrl,
	)
	return i, err
}

const getLastMessagesForConversations = `-- name: GetLastMessagesForConversations :many
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content,
       m.parent_id, m.forwarded_message_id,
       m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at,
       u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.id IN (
  SELECT m2.id FROM messages m2
  WHERE m2.deleted_at IS NULL
    AND m2.conversation_id IN (/*SLICE:conversation_ids*/?)
    AND m2.id = (
      SELECT m3.id FROM messages m3
      WHERE m3.conversation_id = m2.conversation_id AND m3.deleted_at IS NULL
      ORDER BY m3.created_at DESC, m3.id DESC
      LIMIT 1
    )
)
ORDER BY m.created_at DESC
`

type GetLastMessagesForConversationsRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) GetLastMessagesForConversations(ctx context.Context, conversationIds []string) ([]GetLastMessagesForConversationsRow, error) {
	query := getLastMessagesForConversations
	var queryParams []interface{}
	if len(conversationIds) > 0 {
		for _, v := range conversationIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", strings.Repeat(",?", len(conversationIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:conversation_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLastMessagesForConversationsRow
	for rows.Next() {
		var i GetLastMessagesForConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderID,
			&i.Content,
			&i.SearchContent,
			&i.ParentID,
			&i.ForwardedMessageID,
			&i.Pinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageAttachmentByID = `-- name: GetMessageAttachmentByID :one
SELECT id, message_id, file_name, file_size, content_type, storage_path, created_at FROM message_attachments WHERE id = ?
`

func (q *Queries) GetMessageAttachmentByID(ctx context.Context, id string) (MessageAttachment, error) {
	row := q.db.QueryRowContext(ctx, getMessageAttachmentByID, id)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageAttachmentByIDAndConversation = `-- name: GetMessageAttachmentByIDAndConversation :one
SELECT ma.id, ma.message_id, ma.file_name, ma.file_size, ma.content_type, ma.storage_path, ma.created_at
FROM message_attachments ma
JOIN messages m ON m.id = ma.message_id
WHERE ma.id = ? AND m.conversation_id = ?
`

type GetMessageAttachmentByIDAndConversationParams struct {
	ID             string
	ConversationID string
}

// Fetch an attachment by ID, joining to its message to verify the attachment
// actually belongs to the given conversation. Used by the download endpoint
// to prevent cross-conversation IDOR (passing convA in the path while
// requesting an attachment from convB).
func (q *Queries) GetMessageAttachmentByIDAndConversation(ctx context.Context, arg GetMessageAttachmentByIDAndConversationParams) (MessageAttachment, error) {
	row := q.db.QueryRowContext(ctx, getMessageAttachmentByIDAndConversation, arg.ID, arg.ConversationID)
	var i MessageAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content, m.parent_id, m.forwarded_message_id, m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at, u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.id = ? AND m.conversation_id = ? AND m.deleted_at IS NULL
`

type GetMessageByIDParams struct {
	ID             string
	ConversationID string
}

type GetMessageByIDRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) GetMessageByID(ctx context.Context, arg GetMessageByIDParams) (GetMessageByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, arg.ID, arg.ConversationID)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderID,
		&i.Content,
		&i.SearchContent,
		&i.ParentID,
		&i.ForwardedMessageID,
		&i.Pinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderAvatarUrl,
	)
	return i, err
}

const getMessageByIDAnyConv = `-- name: GetMessageByIDAnyConv :one
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content, m.parent_id, m.forwarded_message_id, m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at, u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.id = ? AND m.deleted_at IS NULL
`

type GetMessageByIDAnyConvRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) GetMessageByIDAnyConv(ctx context.Context, id string) (GetMessageByIDAnyConvRow, error) {
	row := q.db.QueryRowContext(ctx, getMessageByIDAnyConv, id)
	var i GetMessageByIDAnyConvRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.SenderID,
		&i.Content,
		&i.SearchContent,
		&i.ParentID,
		&i.ForwardedMessageID,
		&i.Pinned,
		&i.PinnedAt,
		&i.PinnedBy,
		&i.EditedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.SenderName,
		&i.SenderEmail,
		&i.SenderAvatarUrl,
	)
	return i, err
}

const getReactionsForMessages = `-- name: GetReactionsForMessages :many
SELECT message_id, user_id, org_id, emoji, created_at
FROM message_reactions
WHERE message_id IN (/*SLICE:message_ids*/?)
ORDER BY created_at ASC
`

func (q *Queries) GetReactionsForMessages(ctx context.Context, messageIds []string) ([]MessageReaction, error) {
	query := getReactionsForMessages
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.OrgID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessageAttachments = `-- name: ListMessageAttachments :many
SELECT id, message_id, file_name, file_size, content_type, storage_path, created_at FROM message_attachments
WHERE message_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessageAttachments(ctx context.Context, messageID string) ([]MessageAttachment, error) {
	rows, err := q.db.QueryContext(ctx, listMessageAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageAttachment
	for rows.Next() {
		var i MessageAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FileName,
			&i.FileSize,
			&i.ContentType,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content, m.parent_id, m.forwarded_message_id, m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at, u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = ?1 AND m.org_id = ?2 AND m.deleted_at IS NULL
  AND (
    ?3 = '' OR ?4 = ''
    OR m.created_at < ?3
    OR (m.created_at = ?3 AND m.id < ?4)
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT ?5
`

type ListMessagesParams struct {
	ConversationID  string
	OrgID           string
	CursorCreatedAt interface{}
	CursorID        interface{}
	LimitVal        int64
}

type ListMessagesRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.ConversationID,
		arg.OrgID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderID,
			&i.Content,
			&i.SearchContent,
			&i.ParentID,
			&i.ForwardedMessageID,
			&i.Pinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactionCounts = `-- name: ListReactionCounts :many
SELECT message_id, emoji, COUNT(*) AS count
FROM message_reactions
WHERE message_id IN (/*SLICE:message_ids*/?)
GROUP BY message_id, emoji
ORDER BY message_id, emoji
`

type ListReactionCountsRow struct {
	MessageID string
	Emoji     string
	Count     int64
}

func (q *Queries) ListReactionCounts(ctx context.Context, messageIds []string) ([]ListReactionCountsRow, error) {
	query := listReactionCounts
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReactionCountsRow
	for rows.Next() {
		var i ListReactionCountsRow
		if err := rows.Scan(&i.MessageID, &i.Emoji, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReactions = `-- name: ListReactions :many
SELECT message_id, user_id, org_id, emoji, created_at
FROM message_reactions
WHERE message_id IN (/*SLICE:message_ids*/?)
ORDER BY created_at ASC
`

func (q *Queries) ListReactions(ctx context.Context, messageIds []string) ([]MessageReaction, error) {
	query := listReactions
	var queryParams []interface{}
	if len(messageIds) > 0 {
		for _, v := range messageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(messageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MessageReaction
	for rows.Next() {
		var i MessageReaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.OrgID,
			&i.Emoji,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplies = `-- name: ListReplies :many
SELECT m.id, m.conversation_id, m.org_id, m.sender_id, m.content, m.search_content, m.parent_id, m.forwarded_message_id, m.pinned, m.pinned_at, m.pinned_by, m.edited_at, m.deleted_at, m.created_at, u.name AS sender_name, u.email AS sender_email, u.avatar_url AS sender_avatar_url
FROM messages m
INNER JOIN users u ON u.id = m.sender_id
WHERE m.conversation_id = ?1 AND m.org_id = ?2 AND m.parent_id = ?3 AND m.deleted_at IS NULL
  AND (
    ?4 = '' OR ?5 = ''
    OR m.created_at < ?4
    OR (m.created_at = ?4 AND m.id < ?5)
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT ?6
`

type ListRepliesParams struct {
	ConversationID  string
	OrgID           string
	ParentID        *string
	CursorCreatedAt interface{}
	CursorID        interface{}
	LimitVal        int64
}

type ListRepliesRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplies,
		arg.ConversationID,
		arg.OrgID,
		arg.ParentID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderID,
			&i.Content,
			&i.SearchContent,
			&i.ParentID,
			&i.ForwardedMessageID,
			&i.Pinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinMessage = `-- name: PinMessage :exec
UPDATE messages
SET pinned = 1, pinned_at = datetime('now'), pinned_by = ?
WHERE id = ? AND conversation_id = ?
`

type PinMessageParams struct {
	PinnedBy       *string
	ID             string
	ConversationID string
}

func (q *Queries) PinMessage(ctx context.Context, arg PinMessageParams) error {
	_, err := q.db.ExecContext(ctx, pinMessage, arg.PinnedBy, arg.ID, arg.ConversationID)
	return err
}

const removeReaction = `-- name: RemoveReaction :execrows
DELETE FROM message_reactions WHERE message_id = ? AND user_id = ? AND emoji = ?
`

type RemoveReactionParams struct {
	MessageID string
	UserID    string
	Emoji     string
}

func (q *Queries) RemoveReaction(ctx context.Context, arg RemoveReactionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeReaction, arg.MessageID, arg.UserID, arg.Emoji)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const searchMessages = `-- name: SearchMessages :many
WITH RECURSIVE conv_with_link AS (
  -- anchor: conversations that directly have a project link
  SELECT c.id AS conv_id
  FROM conversations c
  WHERE EXISTS (SELECT 1 FROM channel_project_links cpl WHERE cpl.channel_id = c.id)
    AND c.org_id = ?2 AND c.deleted_at IS NULL
  UNION ALL
  -- recurse: children of linked conversations (descendants inherit access)
  SELECT c.id
  FROM conversations c
  JOIN conv_with_link p ON c.parent_id = p.conv_id
  WHERE c.org_id = ?2 AND c.deleted_at IS NULL
),
fts_results AS (
  SELECT
    message_id,
    bm25(messages_fts) AS rank_val,
    snippet(messages_fts, 3, '<mark>', '</mark>', '...', 48) AS snippet
  FROM messages_fts
  WHERE messages_fts.content MATCH ?15
  UNION
  SELECT
    message_id,
    bm25(messages_fts) AS rank_val,
    snippet(messages_fts, 3, '<mark>', '</mark>', '...', 48) AS snippet
  FROM messages_fts
  WHERE messages_fts.attachment_names MATCH ?15
)
SELECT
  m.id,
  m.conversation_id,
  m.org_id,
  m.sender_id,
  m.content,
  m.parent_id,
  m.forwarded_message_id,
  m.pinned,
  m.pinned_at,
  m.pinned_by,
  m.edited_at,
  m.deleted_at,
  m.created_at,
  u.name AS sender_name,
  u.email AS sender_email,
  u.avatar_url AS sender_avatar_url,
  c.name AS conversation_name,
  c.type AS conversation_type,
  CASE WHEN ma.message_id IS NOT NULL THEN 1 ELSE 0 END AS has_attachment,
  f.rank_val,
  f.snippet
FROM fts_results f
JOIN messages m ON m.id = f.message_id
JOIN users u ON u.id = m.sender_id
JOIN conversations c ON c.id = m.conversation_id
LEFT JOIN (
  SELECT message_id FROM message_attachments GROUP BY message_id
) ma ON ma.message_id = m.id
LEFT JOIN conversation_members cm
  ON cm.conversation_id = m.conversation_id AND cm.user_id = ?1
WHERE m.org_id = ?2
  AND m.deleted_at IS NULL
  AND (
    cm.user_id IS NOT NULL
    OR (?3 = 1 AND c.id IN (SELECT conv_id FROM conv_with_link))
  )
  AND (
    ?4 = 'all'
    OR (?4 = 'workspace' AND c.type = 'channel')
    OR (?4 = 'dm' AND c.type IN ('direct', 'group'))
  )
  AND (?5 = '' OR m.conversation_id = ?5)
  AND (?6 = '' OR m.sender_id = ?6)
  AND (?7 = 0 OR ma.message_id IS NOT NULL)
  AND (?8 = 0 OR m.content LIKE '%http://%' OR m.content LIKE '%https://%')
  AND (?9 = 0 OR m.pinned = 1)
  AND (?10 = '' OR m.created_at >= ?10)
  AND (?11 = '' OR m.created_at <= ?11)
  AND (
    ?12 = '' OR ?13 = ''
    OR m.created_at < ?12
    OR (m.created_at = ?12 AND m.id < ?13)
  )
ORDER BY f.rank_val ASC, m.created_at DESC, m.id DESC
LIMIT ?14
`

type SearchMessagesParams struct {
	UserID               string
	OrgID                string
	IncludeProjectLinked interface{}
	Scope                interface{}
	ConversationID       interface{}
	SenderID             interface{}
	HasAttachment        interface{}
	HasLink              interface{}
	IsPinned             interface{}
	After                interface{}
	Before               interface{}
	CursorCreatedAt      interface{}
	CursorID             interface{}
	LimitVal             int64
	Query                string
}

type SearchMessagesRow struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
	SenderName         string
	SenderEmail        string
	SenderAvatarUrl    *string
	ConversationName   string
	ConversationType   string
	HasAttachment      int64
	RankVal            float64
	Snippet            string
}

// Use a CTE so MATCH lives in its own isolated scope; SQLite FTS5 forbids
// MATCH in an OR context when joined to real tables. UNION covers both the
// indexed `content` column and `attachment_names` column.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]SearchMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMessages,
		arg.UserID,
		arg.OrgID,
		arg.IncludeProjectLinked,
		arg.Scope,
		arg.ConversationID,
		arg.SenderID,
		arg.HasAttachment,
		arg.HasLink,
		arg.IsPinned,
		arg.After,
		arg.Before,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMessagesRow
	for rows.Next() {
		var i SearchMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.SenderID,
			&i.Content,
			&i.ParentID,
			&i.ForwardedMessageID,
			&i.Pinned,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EditedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderName,
			&i.SenderEmail,
			&i.SenderAvatarUrl,
			&i.ConversationName,
			&i.ConversationType,
			&i.HasAttachment,
			&i.RankVal,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages
SET deleted_at = datetime('now')
WHERE id = ? AND conversation_id = ?
`

type SoftDeleteMessageParams struct {
	ID             string
	ConversationID string
}

func (q *Queries) SoftDeleteMessage(ctx context.Context, arg SoftDeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteMessage, arg.ID, arg.ConversationID)
	return err
}

const unpinMessage = `-- name: UnpinMessage :exec
UPDATE messages
SET pinned = 0, pinned_at = NULL, pinned_by = NULL
WHERE id = ? AND conversation_id = ?
`

type UnpinMessageParams struct {
	ID             string
	ConversationID string
}

func (q *Queries) UnpinMessage(ctx context.Context, arg UnpinMessageParams) error {
	_, err := q.db.ExecContext(ctx, unpinMessage, arg.ID, arg.ConversationID)
	return err
}

const updateAttachmentMessageID = `-- name: UpdateAttachmentMessageID :exec
UPDATE message_attachments SET message_id = ? WHERE id = ?
`

type UpdateAttachmentMessageIDParams struct {
	MessageID string
	ID        string
}

func (q *Queries) UpdateAttachmentMessageID(ctx context.Context, arg UpdateAttachmentMessageIDParams) error {
	_, err := q.db.ExecContext(ctx, updateAttachmentMessageID, arg.MessageID, arg.ID)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages
SET content = ?, search_content = ?, edited_at = datetime('now')
WHERE id = ? AND conversation_id = ? AND sender_id = ?
`

type UpdateMessageContentParams struct {
	Content        string
	SearchContent  string
	ID             string
	ConversationID string
	SenderID       string
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageContent,
		arg.Content,
		arg.SearchContent,
		arg.ID,
		arg.ConversationID,
		arg.SenderID,
	)
	return err
}
