// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Account struct {
	ID           string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

type Attachment struct {
	ID          string
	TaskID      string
	Filename    string
	ContentType string
	Size        int64
	StoragePath string
	CreatedBy   string
	CreatedAt   string
}

type AuditLog struct {
	ID         string
	OrgID      string
	ActorID    string
	Action     string
	EntityType string
	EntityID   string
	Metadata   string
	CreatedAt  string
}

type ChannelPermission struct {
	ChannelID  string
	Role       string
	Permission string
	Allow      int64
}

type ChannelProjectLink struct {
	ChannelID string
	ProjectID string
}

type ChannelUserOverride struct {
	ChannelID  string
	UserID     string
	Permission string
	Allow      int64
}

type Comment struct {
	ID        string
	OrgID     string
	TaskID    string
	ProjectID string
	AuthorID  string
	Content   string
	ParentID  *string
	DeletedAt *string
	EditedAt  *string
	CreatedAt string
	UpdatedAt string
}

type Conversation struct {
	ID          string
	OrgID       string
	ParentID    *string
	Name        string
	Topic       string
	Type        string
	CreatedBy   string
	PositionKey string
	DeletedAt   *string
	CreatedAt   string
	UpdatedAt   string
}

type ConversationMember struct {
	ConversationID string
	UserID         string
	OrgID          string
	JoinedAt       string
	LastReadAt     string
	Muted          int64
}

type CustomField struct {
	ID        string
	OrgID     string
	ProjectID string
	Name      string
	FieldType string
	Options   string
	Position  int64
	CreatedAt string
	UpdatedAt string
}

type Cycle struct {
	ID          string
	OrgID       string
	ProjectID   string
	Name        string
	Goal        string
	StartsAt    string
	EndsAt      string
	CreatedBy   string
	IsCompleted bool
	IsActive    bool
	CreatedAt   string
	UpdatedAt   string
}

type DashboardPreference struct {
	UserID   string
	OrgID    string
	Sections string
}

type InviteProject struct {
	InviteID  string
	ProjectID string
	Role      string
}

type Label struct {
	ID        string
	OrgID     string
	Name      string
	Color     string
	CreatedAt string
	UpdatedAt string
}

type Message struct {
	ID                 string
	ConversationID     string
	OrgID              string
	SenderID           string
	Content            string
	SearchContent      string
	ParentID           *string
	ForwardedMessageID *string
	Pinned             int64
	PinnedAt           *string
	PinnedBy           *string
	EditedAt           *string
	DeletedAt          *string
	CreatedAt          string
}

type MessageAttachment struct {
	ID          string
	MessageID   string
	FileName    string
	FileSize    int64
	ContentType string
	StoragePath string
	CreatedAt   string
}

type MessageReaction struct {
	MessageID string
	UserID    string
	OrgID     string
	Emoji     string
	CreatedAt string
}

type MessagesFt struct {
	MessageID       string
	OrgID           string
	ConversationID  string
	Content         string
	AttachmentNames string
}

type Notification struct {
	ID         string
	OrgID      string
	UserID     string
	Type       string
	Title      string
	Body       string
	Link       string
	EntityType string
	EntityID   string
	ActorID    *string
	IsRead     int64
	ReadAt     *string
	CreatedAt  string
}

type NotificationPreference struct {
	UserID  string
	Type    string
	Enabled int64
}

type Organization struct {
	ID                       string
	Name                     string
	Slug                     string
	MessageEditWindowMinutes int64
	CreatedAt                string
	UpdatedAt                string
}

type PasswordReset struct {
	ID        string
	AccountID string
	TokenHash string
	ExpiresAt string
	UsedAt    *string
	CreatedAt string
}

type PendingAttachment struct {
	ID             string
	ConversationID string
	FileName       string
	FileSize       int64
	ContentType    string
	StoragePath    string
	CreatedAt      string
	UploadedBy     string
}

type Project struct {
	ID                     string
	OrgID                  string
	Name                   string
	Description            string
	Slug                   string
	Color                  string
	Icon                   string
	CreatedBy              string
	CycleDuration          *int64
	AutoGenerateCycles     bool
	IncompleteTaskHandling string
	StartsAt               *string
	EndsAt                 *string
	IsArchived             bool
	CreatedAt              string
	UpdatedAt              string
}

type ProjectMember struct {
	ProjectID string
	UserID    string
	Role      string
	CreatedAt string
}

type ProjectsFt struct {
	ProjectID string
	OrgID     string
	Name      string
	Slug      string
}

type PushSubscription struct {
	ID        string
	UserID    string
	OrgID     string
	Endpoint  string
	P256dh    string
	AuthKey   string
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    string
	OrgID     string
	Role      string
	ExpiresAt string
	RevokedAt *string
	UserAgent *string
	IpAddress *string
	CreatedAt string
}

type Task struct {
	ID              string
	OrgID           string
	ProjectID       string
	CycleID         *string
	ParentTaskID    *string
	CreatedBy       string
	Title           string
	Description     string
	StatusID        string
	Priority        string
	Estimate        *int64
	PositionKey     string
	SubtaskPosition *string
	TemplateID      *string
	StartedAt       *string
	DueAt           *string
	CompletedAt     *string
	CreatedAt       string
	UpdatedAt       string
}

type TaskActivity struct {
	ID        string
	TaskID    string
	OrgID     string
	ProjectID string
	ActorID   string
	Action    string
	Field     string
	OldValue  string
	NewValue  string
	CreatedAt string
}

type TaskAssignee struct {
	TaskID string
	UserID string
}

type TaskCustomFieldValue struct {
	TaskID        string
	CustomFieldID string
	Value         string
	UpdatedAt     string
}

type TaskDependency struct {
	TaskID       string
	BlocksTaskID string
	CreatedAt    string
}

type TaskLabel struct {
	TaskID  string
	LabelID string
}

type TaskStatus struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	Position  int64
	Category  string
	IsDefault bool
}

type TaskTemplate struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Description       string
	Priority          string
	StatusID          string
	AssigneeIds       string
	Estimate          *int64
	RecurrencePattern string
	RecurrenceDays    string
	NextRunAt         *string
	LastError         *string
	LastErrorAt       *string
	CreatedBy         string
	CreatedAt         string
	UpdatedAt         string
}

type TasksFt struct {
	TaskID      string
	OrgID       string
	ProjectID   string
	Title       string
	Description string
}

type TimeEntry struct {
	ID              string
	TaskID          string
	UserID          string
	Description     string
	StartedAt       string
	EndedAt         *string
	DurationMinutes *int64
	CreatedAt       string
	UpdatedAt       string
}

type User struct {
	ID        string
	AccountID *string
	OrgID     string
	Email     string
	Name      string
	Role      string
	AvatarUrl *string
	IsActive  int64
	CreatedAt string
	UpdatedAt string
}

type UserChannelPreference struct {
	UserID            string
	ConversationID    string
	OrgID             string
	NotificationLevel string
	Muted             int64
	LastReadAt        string
	UpdatedAt         string
}

type UserInvite struct {
	ID        string
	OrgID     string
	Email     *string
	Role      string
	TokenHash string
	InvitedBy string
	MaxUses   *int64
	UseCount  int64
	ExpiresAt string
	CreatedAt string
}

type UserInviteAcceptance struct {
	ID        string
	InviteID  string
	UserID    string
	CreatedAt string
}

type UserPreference struct {
	UserID               string
	Theme                string
	Language             string
	Timezone             string
	EmailNotifications   int64
	DesktopNotifications int64
	NotificationSounds   int64
	SidebarCollapsed     int64
	MotionSettings       string
	CreatedAt            string
	UpdatedAt            string
}

type UserPresence struct {
	UserID    string
	OrgID     string
	Status    string
	LastSeen  string
	UpdatedAt string
}

type View struct {
	ID        string
	OrgID     string
	ProjectID *string
	CreatedBy string
	Name      string
	Layout    string
	Filters   string
	CreatedAt string
	UpdatedAt string
}

type ViewPin struct {
	ViewID    string
	UserID    string
	CreatedAt string
}

type VoiceParticipant struct {
	ID             string
	ConversationID string
	OrgID          string
	UserID         string
	Muted          int64
	Deafened       int64
	ConnectionID   string
	JoinedAt       string
}
