// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlc

import (
	"context"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = ? AND is_read = 0
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (id, org_id, user_id, type, title, body, link, entity_type, entity_id, actor_id, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	ID         string
	OrgID      string
	UserID     string
	Type       string
	Title      string
	Body       string
	Link       string
	EntityType string
	EntityID   string
	ActorID    *string
	CreatedAt  string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.ID,
		arg.OrgID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Link,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.CreatedAt,
	)
	return err
}

const findDueNotificationTasks = `-- name: FindDueNotificationTasks :many
SELECT t.id AS task_id, t.title AS task_title, t.due_at, t.status_id,
       ta.user_id AS assignee_id, t.org_id, t.project_id,
       p.slug AS project_slug
FROM tasks t
JOIN task_assignees ta ON ta.task_id = t.id
JOIN projects p ON p.id = t.project_id
WHERE t.due_at IS NOT NULL
  AND t.completed_at IS NULL
  AND (
    (t.due_at < ?1 AND t.due_at >= ?2)
    OR (t.due_at >= ?1 AND t.due_at < ?3)
  )
  AND NOT EXISTS (
    SELECT 1 FROM notifications n
    WHERE n.entity_type = 'task'
      AND n.entity_id = t.id
      AND n.user_id = ta.user_id
      AND n.type IN (?4, ?5)
      AND n.created_at > datetime('now', '-24 hours')
  )
`

type FindDueNotificationTasksParams struct {
	Now          *string
	OverdueStart *string
	DueSoonEnd   *string
	DueSoonType  string
	OverdueType  string
}

type FindDueNotificationTasksRow struct {
	TaskID      string
	TaskTitle   string
	DueAt       *string
	StatusID    string
	AssigneeID  string
	OrgID       string
	ProjectID   string
	ProjectSlug string
}

func (q *Queries) FindDueNotificationTasks(ctx context.Context, arg FindDueNotificationTasksParams) ([]FindDueNotificationTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, findDueNotificationTasks,
		arg.Now,
		arg.OverdueStart,
		arg.DueSoonEnd,
		arg.DueSoonType,
		arg.OverdueType,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindDueNotificationTasksRow
	for rows.Next() {
		var i FindDueNotificationTasksRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskTitle,
			&i.DueAt,
			&i.StatusID,
			&i.AssigneeID,
			&i.OrgID,
			&i.ProjectID,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT n.id, n.org_id, n.user_id, n.type, n.title, n.body, n.link,
       n.entity_type, n.entity_id, n.actor_id,
       n.is_read, n.read_at, n.created_at,
       u.id AS actor_user_id, u.name AS actor_name, u.email AS actor_email, u.avatar_url AS actor_avatar_url,
       COALESCE(p.slug, '') AS project_slug
FROM notifications n
LEFT JOIN users u ON u.id = n.actor_id
LEFT JOIN tasks t ON t.id = n.entity_id AND n.entity_type = 'task'
LEFT JOIN projects p ON p.id = t.project_id
WHERE n.id = ? AND n.user_id = ?
`

type GetNotificationByIDParams struct {
	ID     string
	UserID string
}

type GetNotificationByIDRow struct {
	ID             string
	OrgID          string
	UserID         string
	Type           string
	Title          string
	Body           string
	Link           string
	EntityType     string
	EntityID       string
	ActorID        *string
	IsRead         int64
	ReadAt         *string
	CreatedAt      string
	ActorUserID    *string
	ActorName      *string
	ActorEmail     *string
	ActorAvatarUrl *string
	ProjectSlug    string
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (GetNotificationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Link,
		&i.EntityType,
		&i.EntityID,
		&i.ActorID,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
		&i.ActorUserID,
		&i.ActorName,
		&i.ActorEmail,
		&i.ActorAvatarUrl,
		&i.ProjectSlug,
	)
	return i, err
}

const getNotificationPreferenceByType = `-- name: GetNotificationPreferenceByType :one
SELECT type, enabled FROM notification_preferences WHERE user_id = ? AND type = ?
`

type GetNotificationPreferenceByTypeParams struct {
	UserID string
	Type   string
}

type GetNotificationPreferenceByTypeRow struct {
	Type    string
	Enabled int64
}

func (q *Queries) GetNotificationPreferenceByType(ctx context.Context, arg GetNotificationPreferenceByTypeParams) (GetNotificationPreferenceByTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreferenceByType, arg.UserID, arg.Type)
	var i GetNotificationPreferenceByTypeRow
	err := row.Scan(&i.Type, &i.Enabled)
	return i, err
}

const listNotificationPreferences = `-- name: ListNotificationPreferences :many
SELECT type, enabled FROM notification_preferences WHERE user_id = ?
`

type ListNotificationPreferencesRow struct {
	Type    string
	Enabled int64
}

func (q *Queries) ListNotificationPreferences(ctx context.Context, userID string) ([]ListNotificationPreferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationPreferencesRow
	for rows.Next() {
		var i ListNotificationPreferencesRow
		if err := rows.Scan(&i.Type, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.org_id, n.user_id, n.type, n.title, n.body, n.link,
       n.entity_type, n.entity_id, n.actor_id,
       n.is_read, n.read_at, n.created_at,
       u.id AS actor_user_id, u.name AS actor_name, u.email AS actor_email, u.avatar_url AS actor_avatar_url,
       COALESCE(p.slug, '') AS project_slug
FROM notifications n
LEFT JOIN users u ON u.id = n.actor_id
LEFT JOIN tasks t ON t.id = n.entity_id AND n.entity_type = 'task'
LEFT JOIN projects p ON p.id = t.project_id
WHERE n.user_id = ?1 AND n.org_id = ?2
  AND (?3 = 0 OR n.is_read = 0)
  AND (
    ?4 = '' OR ?5 = ''
    OR n.created_at < ?4
    OR (n.created_at = ?4 AND n.id < ?5)
  )
ORDER BY n.created_at DESC, n.id DESC
LIMIT ?6
`

type ListNotificationsParams struct {
	UserID          string
	OrgID           string
	UnreadOnly      interface{}
	CursorCreatedAt interface{}
	CursorID        interface{}
	LimitVal        int64
}

type ListNotificationsRow struct {
	ID             string
	OrgID          string
	UserID         string
	Type           string
	Title          string
	Body           string
	Link           string
	EntityType     string
	EntityID       string
	ActorID        *string
	IsRead         int64
	ReadAt         *string
	CreatedAt      string
	ActorUserID    *string
	ActorName      *string
	ActorEmail     *string
	ActorAvatarUrl *string
	ProjectSlug    string
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications,
		arg.UserID,
		arg.OrgID,
		arg.UnreadOnly,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Link,
			&i.EntityType,
			&i.EntityID,
			&i.ActorID,
			&i.IsRead,
			&i.ReadAt,
			&i.CreatedAt,
			&i.ActorUserID,
			&i.ActorName,
			&i.ActorEmail,
			&i.ActorAvatarUrl,
			&i.ProjectSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET is_read = 1, read_at = datetime('now')
WHERE user_id = ? AND is_read = 0
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET is_read = 1, read_at = datetime('now')
WHERE id = ? AND user_id = ?
`

type MarkNotificationReadParams struct {
	ID     string
	UserID string
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNotificationPreference = `-- name: SetNotificationPreference :exec
INSERT INTO notification_preferences (user_id, type, enabled)
VALUES (?, ?, ?)
ON CONFLICT(user_id, type) DO UPDATE SET enabled = excluded.enabled
`

type SetNotificationPreferenceParams struct {
	UserID  string
	Type    string
	Enabled int64
}

func (q *Queries) SetNotificationPreference(ctx context.Context, arg SetNotificationPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, setNotificationPreference, arg.UserID, arg.Type, arg.Enabled)
	return err
}
