// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (id, name, slug)
VALUES (?, ?, ?)
`

type CreateOrganizationParams struct {
	ID   string
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = ?
`

func (q *Queries) DeleteOrganization(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, message_edit_window_minutes, created_at, updated_at
FROM organizations
WHERE id = ?
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MessageEditWindowMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, message_edit_window_minutes, created_at, updated_at
FROM organizations
WHERE slug = ?
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.MessageEditWindowMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationsByAccount = `-- name: ListOrganizationsByAccount :many
SELECT o.id, o.name, o.slug, o.message_edit_window_minutes, o.created_at, o.updated_at,
       u.role AS user_role, u.is_active AS user_is_active
FROM organizations o
INNER JOIN users u ON u.org_id = o.id
WHERE u.account_id = ?
ORDER BY u.updated_at DESC
`

type ListOrganizationsByAccountRow struct {
	ID                       string
	Name                     string
	Slug                     string
	MessageEditWindowMinutes int64
	CreatedAt                string
	UpdatedAt                string
	UserRole                 string
	UserIsActive             int64
}

func (q *Queries) ListOrganizationsByAccount(ctx context.Context, accountID *string) ([]ListOrganizationsByAccountRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrganizationsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationsByAccountRow
	for rows.Next() {
		var i ListOrganizationsByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.MessageEditWindowMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserRole,
			&i.UserIsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationCount = `-- name: OrganizationCount :one
SELECT COUNT(*) FROM organizations
`

func (q *Queries) OrganizationCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, organizationCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const organizationExists = `-- name: OrganizationExists :one
SELECT COUNT(*) > 0 FROM organizations
`

func (q *Queries) OrganizationExists(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, organizationExists)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET name = ?, slug = ?, message_edit_window_minutes = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateOrganizationParams struct {
	Name                     string
	Slug                     string
	MessageEditWindowMinutes int64
	ID                       string
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, updateOrganization,
		arg.Name,
		arg.Slug,
		arg.MessageEditWindowMinutes,
		arg.ID,
	)
	return err
}
