// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package sqlc

import (
	"context"
)

const createPasswordReset = `-- name: CreatePasswordReset :exec
INSERT INTO password_resets (id, account_id, token_hash, expires_at)
VALUES (?, ?, ?, ?)
`

type CreatePasswordResetParams struct {
	ID        string
	AccountID string
	TokenHash string
	ExpiresAt string
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordReset,
		arg.ID,
		arg.AccountID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const deleteUsedAndExpiredPasswordResets = `-- name: DeleteUsedAndExpiredPasswordResets :execrows
DELETE FROM password_resets
WHERE used_at IS NOT NULL OR expires_at < datetime('now')
`

// Cleanup for rows that no longer serve any purpose: consumed tokens and
// expired-but-never-used ones.
func (q *Queries) DeleteUsedAndExpiredPasswordResets(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUsedAndExpiredPasswordResets)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPasswordResetByTokenHash = `-- name: GetPasswordResetByTokenHash :one
SELECT id, account_id, token_hash, expires_at, used_at, created_at
FROM password_resets
WHERE token_hash = ?
`

func (q *Queries) GetPasswordResetByTokenHash(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByTokenHash, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :execrows
UPDATE password_resets
SET used_at = datetime('now')
WHERE id = ? AND used_at IS NULL
`

// Conditional update makes the token atomically single-use: two concurrent
// confirms with the same valid token can't both pass (only one UPDATE wins).
func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPasswordResetUsed, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
