// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending.sql

package sqlc

import (
	"context"
)

const createPendingAttachment = `-- name: CreatePendingAttachment :exec
INSERT INTO pending_attachments (id, conversation_id, file_name, file_size, content_type, storage_path, uploaded_by)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePendingAttachmentParams struct {
	ID             string
	ConversationID string
	FileName       string
	FileSize       int64
	ContentType    string
	StoragePath    string
	UploadedBy     string
}

func (q *Queries) CreatePendingAttachment(ctx context.Context, arg CreatePendingAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createPendingAttachment,
		arg.ID,
		arg.ConversationID,
		arg.FileName,
		arg.FileSize,
		arg.ContentType,
		arg.StoragePath,
		arg.UploadedBy,
	)
	return err
}

const deletePendingAttachment = `-- name: DeletePendingAttachment :exec
DELETE FROM pending_attachments WHERE id = ?
`

func (q *Queries) DeletePendingAttachment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePendingAttachment, id)
	return err
}

const deletePendingAttachmentsOlderThan = `-- name: DeletePendingAttachmentsOlderThan :many
DELETE FROM pending_attachments WHERE created_at < ?
RETURNING id, conversation_id, file_name, file_size, content_type, storage_path, created_at, uploaded_by
`

func (q *Queries) DeletePendingAttachmentsOlderThan(ctx context.Context, createdAt string) ([]PendingAttachment, error) {
	rows, err := q.db.QueryContext(ctx, deletePendingAttachmentsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingAttachment
	for rows.Next() {
		var i PendingAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.FileName,
			&i.FileSize,
			&i.ContentType,
			&i.StoragePath,
			&i.CreatedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingAttachmentByID = `-- name: GetPendingAttachmentByID :one
SELECT id, conversation_id, file_name, file_size, content_type, storage_path, created_at, uploaded_by FROM pending_attachments WHERE id = ? AND uploaded_by = ?
`

type GetPendingAttachmentByIDParams struct {
	ID         string
	UploadedBy string
}

func (q *Queries) GetPendingAttachmentByID(ctx context.Context, arg GetPendingAttachmentByIDParams) (PendingAttachment, error) {
	row := q.db.QueryRowContext(ctx, getPendingAttachmentByID, arg.ID, arg.UploadedBy)
	var i PendingAttachment
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.FileName,
		&i.FileSize,
		&i.ContentType,
		&i.StoragePath,
		&i.CreatedAt,
		&i.UploadedBy,
	)
	return i, err
}
