// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preferences.sql

package sqlc

import (
	"context"
)

const getChannelPreference = `-- name: GetChannelPreference :one
SELECT user_id, conversation_id, org_id, notification_level, muted, last_read_at, updated_at FROM user_channel_preferences
WHERE user_id = ? AND conversation_id = ?
`

type GetChannelPreferenceParams struct {
	UserID         string
	ConversationID string
}

func (q *Queries) GetChannelPreference(ctx context.Context, arg GetChannelPreferenceParams) (UserChannelPreference, error) {
	row := q.db.QueryRowContext(ctx, getChannelPreference, arg.UserID, arg.ConversationID)
	var i UserChannelPreference
	err := row.Scan(
		&i.UserID,
		&i.ConversationID,
		&i.OrgID,
		&i.NotificationLevel,
		&i.Muted,
		&i.LastReadAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationLevel = `-- name: GetNotificationLevel :one
SELECT notification_level FROM user_channel_preferences
WHERE user_id = ? AND conversation_id = ?
`

type GetNotificationLevelParams struct {
	UserID         string
	ConversationID string
}

func (q *Queries) GetNotificationLevel(ctx context.Context, arg GetNotificationLevelParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNotificationLevel, arg.UserID, arg.ConversationID)
	var notification_level string
	err := row.Scan(&notification_level)
	return notification_level, err
}

const listChannelsForUser = `-- name: ListChannelsForUser :many
SELECT user_id, conversation_id, org_id, notification_level, muted, last_read_at, updated_at FROM user_channel_preferences
WHERE user_id = ?
ORDER BY conversation_id
`

func (q *Queries) ListChannelsForUser(ctx context.Context, userID string) ([]UserChannelPreference, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserChannelPreference
	for rows.Next() {
		var i UserChannelPreference
		if err := rows.Scan(
			&i.UserID,
			&i.ConversationID,
			&i.OrgID,
			&i.NotificationLevel,
			&i.Muted,
			&i.LastReadAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelLastRead = `-- name: UpdateChannelLastRead :exec
UPDATE user_channel_preferences SET last_read_at = datetime('now'), updated_at = datetime('now')
WHERE user_id = ? AND conversation_id = ?
`

type UpdateChannelLastReadParams struct {
	UserID         string
	ConversationID string
}

func (q *Queries) UpdateChannelLastRead(ctx context.Context, arg UpdateChannelLastReadParams) error {
	_, err := q.db.ExecContext(ctx, updateChannelLastRead, arg.UserID, arg.ConversationID)
	return err
}

const upsertChannelMute = `-- name: UpsertChannelMute :exec
INSERT INTO user_channel_preferences (user_id, conversation_id, org_id, muted, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id, conversation_id) DO UPDATE SET
    muted = excluded.muted,
    updated_at = excluded.updated_at
`

type UpsertChannelMuteParams struct {
	UserID         string
	ConversationID string
	OrgID          string
	Muted          int64
}

func (q *Queries) UpsertChannelMute(ctx context.Context, arg UpsertChannelMuteParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelMute,
		arg.UserID,
		arg.ConversationID,
		arg.OrgID,
		arg.Muted,
	)
	return err
}

const upsertChannelNotificationLevel = `-- name: UpsertChannelNotificationLevel :exec
INSERT INTO user_channel_preferences (user_id, conversation_id, org_id, notification_level, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT(user_id, conversation_id) DO UPDATE SET
    notification_level = excluded.notification_level,
    updated_at = excluded.updated_at
`

type UpsertChannelNotificationLevelParams struct {
	UserID            string
	ConversationID    string
	OrgID             string
	NotificationLevel string
}

func (q *Queries) UpsertChannelNotificationLevel(ctx context.Context, arg UpsertChannelNotificationLevelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelNotificationLevel,
		arg.UserID,
		arg.ConversationID,
		arg.OrgID,
		arg.NotificationLevel,
	)
	return err
}

const upsertChannelPreference = `-- name: UpsertChannelPreference :exec
INSERT INTO user_channel_preferences (user_id, conversation_id, org_id, notification_level, muted, last_read_at, updated_at)
VALUES (?, ?, ?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT(user_id, conversation_id) DO UPDATE SET
    notification_level = excluded.notification_level,
    muted = excluded.muted,
    updated_at = excluded.updated_at
`

type UpsertChannelPreferenceParams struct {
	UserID            string
	ConversationID    string
	OrgID             string
	NotificationLevel string
	Muted             int64
}

func (q *Queries) UpsertChannelPreference(ctx context.Context, arg UpsertChannelPreferenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelPreference,
		arg.UserID,
		arg.ConversationID,
		arg.OrgID,
		arg.NotificationLevel,
		arg.Muted,
	)
	return err
}
