// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: presence.sql

package sqlc

import (
	"context"
	"strings"
)

const deletePresence = `-- name: DeletePresence :execrows
DELETE FROM user_presence WHERE user_id = ? AND org_id = ?
`

type DeletePresenceParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) DeletePresence(ctx context.Context, arg DeletePresenceParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePresence, arg.UserID, arg.OrgID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPresence = `-- name: GetPresence :one
SELECT user_id, org_id, status, last_seen, updated_at FROM user_presence WHERE user_id = ? AND org_id = ?
`

type GetPresenceParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) GetPresence(ctx context.Context, arg GetPresenceParams) (UserPresence, error) {
	row := q.db.QueryRowContext(ctx, getPresence, arg.UserID, arg.OrgID)
	var i UserPresence
	err := row.Scan(
		&i.UserID,
		&i.OrgID,
		&i.Status,
		&i.LastSeen,
		&i.UpdatedAt,
	)
	return i, err
}

const getPresenceForUsers = `-- name: GetPresenceForUsers :many
SELECT user_id, org_id, status, last_seen, updated_at FROM user_presence
WHERE org_id = ? AND user_id IN (/*SLICE:user_ids*/?)
`

type GetPresenceForUsersParams struct {
	OrgID   string
	UserIds []string
}

func (q *Queries) GetPresenceForUsers(ctx context.Context, arg GetPresenceForUsersParams) ([]UserPresence, error) {
	query := getPresenceForUsers
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrgID)
	if len(arg.UserIds) > 0 {
		for _, v := range arg.UserIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(arg.UserIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPresence
	for rows.Next() {
		var i UserPresence
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.Status,
			&i.LastSeen,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgPresence = `-- name: ListOrgPresence :many
SELECT up.user_id, up.org_id, up.status, up.last_seen, up.updated_at, u.name AS user_name, u.email AS user_email, u.avatar_url AS user_avatar_url
FROM user_presence up
INNER JOIN users u ON u.id = up.user_id
WHERE up.org_id = ?
ORDER BY
  CASE up.status WHEN 'online' THEN 0 WHEN 'away' THEN 1 ELSE 2 END,
  u.name ASC
`

type ListOrgPresenceRow struct {
	UserID        string
	OrgID         string
	Status        string
	LastSeen      string
	UpdatedAt     string
	UserName      string
	UserEmail     string
	UserAvatarUrl *string
}

func (q *Queries) ListOrgPresence(ctx context.Context, orgID string) ([]ListOrgPresenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listOrgPresence, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrgPresenceRow
	for rows.Next() {
		var i ListOrgPresenceRow
		if err := rows.Scan(
			&i.UserID,
			&i.OrgID,
			&i.Status,
			&i.LastSeen,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPresence = `-- name: UpsertPresence :exec
INSERT INTO user_presence (user_id, org_id, status, last_seen, updated_at)
VALUES (?, ?, ?, datetime('now'), datetime('now'))
ON CONFLICT(user_id, org_id) DO UPDATE SET
    status = excluded.status,
    last_seen = excluded.last_seen,
    updated_at = excluded.updated_at
`

type UpsertPresenceParams struct {
	UserID string
	OrgID  string
	Status string
}

func (q *Queries) UpsertPresence(ctx context.Context, arg UpsertPresenceParams) error {
	_, err := q.db.ExecContext(ctx, upsertPresence, arg.UserID, arg.OrgID, arg.Status)
	return err
}
