// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package sqlc

import (
	"context"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
SELECT ?, u.id, ?
FROM users u
JOIN projects p ON p.id = ?
WHERE u.id = ? AND u.org_id = p.org_id
`

type AddProjectMemberParams struct {
	ProjectID string
	Role      string
	ID        string
	ID_2      string
}

func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, addProjectMember,
		arg.ProjectID,
		arg.Role,
		arg.ID,
		arg.ID_2,
	)
	return err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT u.id, u.name, u.email, u.avatar_url, u.role,
       COALESCE(pm.role, '') AS project_role
FROM users u
LEFT JOIN project_members pm ON pm.user_id = u.id AND pm.project_id = ?1
WHERE u.id = ?2 AND u.org_id = ?3
`

type GetProjectMemberParams struct {
	ProjectID string
	UserID    string
	OrgID     string
}

type GetProjectMemberRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   *string
	Role        string
	ProjectRole string
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectMember, arg.ProjectID, arg.UserID, arg.OrgID)
	var i GetProjectMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.Role,
		&i.ProjectRole,
	)
	return i, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id, u.name, u.email, u.avatar_url, u.role AS org_role, pm.role AS project_role
FROM users u
JOIN project_members pm ON pm.user_id = u.id AND pm.project_id = ?1
WHERE u.org_id = ?2
  AND (?3 IS NULL OR ?3 = '' OR instr(lower(u.name), lower(?3)) > 0)
  AND (
    (?4 = '' AND ?5 = '')
    OR (u.name > ?4)
    OR (u.name = ?4 AND u.id > ?5)
  )
ORDER BY u.name ASC, u.id ASC
LIMIT ?6
`

type ListProjectMembersParams struct {
	ProjectID  string
	OrgID      string
	Search     interface{}
	CursorName interface{}
	CursorID   interface{}
	LimitVal   int64
}

type ListProjectMembersRow struct {
	ID          string
	Name        string
	Email       string
	AvatarUrl   *string
	OrgRole     string
	ProjectRole string
}

// Only explicit project members (rows in project_members). Org owners/admins
// have implicit access via EnsureProjectAccess but are not listed here, so the
// list reflects exactly who can be added/removed. u.role is the org role
// (used to decide whether the per-project role is meaningful/overridable);
// pm.role is the project role (the effective role for project-scoped users).
func (q *Queries) ListProjectMembers(ctx context.Context, arg ListProjectMembersParams) ([]ListProjectMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectMembers,
		arg.ProjectID,
		arg.OrgID,
		arg.Search,
		arg.CursorName,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.OrgRole,
			&i.ProjectRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectMemberships = `-- name: ListUserProjectMemberships :many
SELECT pm.project_id, p.name, p.color, p.icon, pm.role
FROM project_members pm
JOIN projects p ON p.id = pm.project_id
WHERE pm.user_id = ? AND p.org_id = ?
ORDER BY p.name ASC
`

type ListUserProjectMembershipsParams struct {
	UserID string
	OrgID  string
}

type ListUserProjectMembershipsRow struct {
	ProjectID string
	Name      string
	Color     string
	Icon      string
	Role      string
}

func (q *Queries) ListUserProjectMemberships(ctx context.Context, arg ListUserProjectMembershipsParams) ([]ListUserProjectMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserProjectMemberships, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserProjectMembershipsRow
	for rows.Next() {
		var i ListUserProjectMembershipsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Icon,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = ? AND user_id = ?
`

type RemoveProjectMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = ?
WHERE project_id = ? AND user_id = ?
`

type UpdateProjectMemberRoleParams struct {
	Role      string
	ProjectID string
	UserID    string
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectMemberRole, arg.Role, arg.ProjectID, arg.UserID)
	return err
}
