// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, org_id, name, description, slug, color, icon, created_by, cycle_duration, auto_generate_cycles, incomplete_task_handling, starts_at, ends_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)
`

type CreateProjectParams struct {
	ID                     string
	OrgID                  string
	Name                   string
	Description            string
	Slug                   string
	Color                  string
	Icon                   string
	CreatedBy              string
	CycleDuration          *int64
	AutoGenerateCycles     bool
	IncompleteTaskHandling string
	StartsAt               *string
	EndsAt                 *string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Description,
		arg.Slug,
		arg.Color,
		arg.Icon,
		arg.CreatedBy,
		arg.CycleDuration,
		arg.AutoGenerateCycles,
		arg.IncompleteTaskHandling,
		arg.StartsAt,
		arg.EndsAt,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE id = ?1 AND org_id = ?2
`

type DeleteProjectParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.OrgID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, org_id, name, description, slug, color, icon, created_by, cycle_duration, auto_generate_cycles, incomplete_task_handling, starts_at, ends_at, is_archived, created_at, updated_at
FROM projects
WHERE id = ?1 AND org_id = ?2
`

type GetProjectByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, arg.ID, arg.OrgID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Color,
		&i.Icon,
		&i.CreatedBy,
		&i.CycleDuration,
		&i.AutoGenerateCycles,
		&i.IncompleteTaskHandling,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, org_id, name, description, slug, color, icon, created_by, cycle_duration, auto_generate_cycles, incomplete_task_handling, starts_at, ends_at, is_archived, created_at, updated_at
FROM projects
WHERE org_id = ?1 AND slug = ?2
`

type GetProjectBySlugParams struct {
	OrgID string
	Slug  string
}

func (q *Queries) GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectBySlug, arg.OrgID, arg.Slug)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Slug,
		&i.Color,
		&i.Icon,
		&i.CreatedBy,
		&i.CycleDuration,
		&i.AutoGenerateCycles,
		&i.IncompleteTaskHandling,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByMembership = `-- name: ListProjectsByMembership :many
SELECT p.id, p.org_id, p.name, p.description, p.slug, p.color, p.icon, p.created_by, p.cycle_duration, p.auto_generate_cycles, p.incomplete_task_handling, p.starts_at, p.ends_at, p.is_archived, p.created_at, p.updated_at
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?1
WHERE p.org_id = ?2 AND (?3 = 1 OR p.is_archived = FALSE)
ORDER BY p.created_at DESC
`

type ListProjectsByMembershipParams struct {
	UserID          string
	OrgID           string
	IncludeArchived interface{}
}

// Projects a project-scoped user (viewer/guest) is an explicit member of.
func (q *Queries) ListProjectsByMembership(ctx context.Context, arg ListProjectsByMembershipParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByMembership, arg.UserID, arg.OrgID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.Color,
			&i.Icon,
			&i.CreatedBy,
			&i.CycleDuration,
			&i.AutoGenerateCycles,
			&i.IncompleteTaskHandling,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByOrg = `-- name: ListProjectsByOrg :many
SELECT id, org_id, name, description, slug, color, icon, created_by, cycle_duration, auto_generate_cycles, incomplete_task_handling, starts_at, ends_at, is_archived, created_at, updated_at
FROM projects
WHERE org_id = ?1 AND (?2 = 1 OR is_archived = FALSE)
ORDER BY created_at DESC
`

type ListProjectsByOrgParams struct {
	OrgID           string
	IncludeArchived interface{}
}

func (q *Queries) ListProjectsByOrg(ctx context.Context, arg ListProjectsByOrgParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByOrg, arg.OrgID, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Slug,
			&i.Color,
			&i.Icon,
			&i.CreatedBy,
			&i.CycleDuration,
			&i.AutoGenerateCycles,
			&i.IncompleteTaskHandling,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProjectArchived = `-- name: SetProjectArchived :exec
UPDATE projects
SET is_archived = ?1, updated_at = datetime('now')
WHERE id = ?2 AND org_id = ?3
`

type SetProjectArchivedParams struct {
	IsArchived bool
	ID         string
	OrgID      string
}

func (q *Queries) SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) error {
	_, err := q.db.ExecContext(ctx, setProjectArchived, arg.IsArchived, arg.ID, arg.OrgID)
	return err
}

const updateProject = `-- name: UpdateProject :exec
UPDATE projects
SET name = ?1, description = ?2, color = ?3, icon = ?4, cycle_duration = ?5, auto_generate_cycles = ?6, incomplete_task_handling = ?7, starts_at = ?8, ends_at = ?9, updated_at = datetime('now')
WHERE id = ?10 AND org_id = ?11
`

type UpdateProjectParams struct {
	Name                   string
	Description            string
	Color                  string
	Icon                   string
	CycleDuration          *int64
	AutoGenerateCycles     bool
	IncompleteTaskHandling string
	StartsAt               *string
	EndsAt                 *string
	ID                     string
	OrgID                  string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) error {
	_, err := q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
		arg.CycleDuration,
		arg.AutoGenerateCycles,
		arg.IncompleteTaskHandling,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}
