// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push_subscriptions.sql

package sqlc

import (
	"context"
)

const createPushSubscription = `-- name: CreatePushSubscription :one
INSERT INTO push_subscriptions (id, user_id, org_id, endpoint, p256dh, auth_key)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth_key = excluded.auth_key
RETURNING id, user_id, org_id, endpoint, p256dh, auth_key, created_at
`

type CreatePushSubscriptionParams struct {
	ID       string
	UserID   string
	OrgID    string
	Endpoint string
	P256dh   string
	AuthKey  string
}

func (q *Queries) CreatePushSubscription(ctx context.Context, arg CreatePushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRowContext(ctx, createPushSubscription,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.Endpoint,
		arg.P256dh,
		arg.AuthKey,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Endpoint,
		&i.P256dh,
		&i.AuthKey,
		&i.CreatedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions
WHERE user_id = ? AND endpoint = ?
`

type DeletePushSubscriptionParams struct {
	UserID   string
	Endpoint string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePushSubscriptionsByUser = `-- name: DeletePushSubscriptionsByUser :execrows
DELETE FROM push_subscriptions
WHERE user_id = ?
`

func (q *Queries) DeletePushSubscriptionsByUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePushSubscriptionsByUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
SELECT id, user_id, org_id, endpoint, p256dh, auth_key, created_at
FROM push_subscriptions
WHERE user_id = ?
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID string) ([]PushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Endpoint,
			&i.P256dh,
			&i.AuthKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
