// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlc

import (
	"context"
)

const recentProjects = `-- name: RecentProjects :many
SELECT id, name, slug, color, updated_at
FROM projects
WHERE org_id = ?1
ORDER BY updated_at DESC
LIMIT ?2
`

type RecentProjectsParams struct {
	OrgID string
	Limit int64
}

type RecentProjectsRow struct {
	ID        string
	Name      string
	Slug      string
	Color     string
	UpdatedAt string
}

func (q *Queries) RecentProjects(ctx context.Context, arg RecentProjectsParams) ([]RecentProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, recentProjects, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentProjectsRow
	for rows.Next() {
		var i RecentProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentProjectsForUser = `-- name: RecentProjectsForUser :many
SELECT p.id, p.name, p.slug, p.color, p.updated_at
FROM projects p
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?1
WHERE p.org_id = ?2
ORDER BY p.updated_at DESC
LIMIT ?3
`

type RecentProjectsForUserParams struct {
	UserID string
	OrgID  string
	Limit  int64
}

type RecentProjectsForUserRow struct {
	ID        string
	Name      string
	Slug      string
	Color     string
	UpdatedAt string
}

// Recent projects scoped to projects the caller is an explicit member of.
// Used for viewer/guest users.
func (q *Queries) RecentProjectsForUser(ctx context.Context, arg RecentProjectsForUserParams) ([]RecentProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, recentProjectsForUser, arg.UserID, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentProjectsForUserRow
	for rows.Next() {
		var i RecentProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentTasks = `-- name: RecentTasks :many
SELECT t.id, t.title, t.project_id, p.name AS project_name, p.slug AS project_slug, p.color AS project_color, t.updated_at
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
WHERE t.org_id = ?1
ORDER BY t.updated_at DESC
LIMIT ?2
`

type RecentTasksParams struct {
	OrgID string
	Limit int64
}

type RecentTasksRow struct {
	ID           string
	Title        string
	ProjectID    string
	ProjectName  string
	ProjectSlug  string
	ProjectColor string
	UpdatedAt    string
}

func (q *Queries) RecentTasks(ctx context.Context, arg RecentTasksParams) ([]RecentTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, recentTasks, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentTasksRow
	for rows.Next() {
		var i RecentTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.ProjectColor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentTasksForUser = `-- name: RecentTasksForUser :many
SELECT t.id, t.title, t.project_id, p.name AS project_name, p.slug AS project_slug, p.color AS project_color, t.updated_at
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
JOIN project_members pm ON pm.project_id = t.project_id AND pm.user_id = ?2
WHERE t.org_id = ?1
ORDER BY t.updated_at DESC
LIMIT ?3
`

type RecentTasksForUserParams struct {
	OrgID  string
	UserID string
	Limit  int64
}

type RecentTasksForUserRow struct {
	ID           string
	Title        string
	ProjectID    string
	ProjectName  string
	ProjectSlug  string
	ProjectColor string
	UpdatedAt    string
}

func (q *Queries) RecentTasksForUser(ctx context.Context, arg RecentTasksForUserParams) ([]RecentTasksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, recentTasksForUser, arg.OrgID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentTasksForUserRow
	for rows.Next() {
		var i RecentTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.ProjectColor,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchChannels = `-- name: SearchChannels :many
WITH RECURSIVE conv_with_link AS (
  SELECT c.id AS conv_id
  FROM conversations c
  WHERE EXISTS (SELECT 1 FROM channel_project_links cpl WHERE cpl.channel_id = c.id)
    AND c.org_id = ?1 AND c.deleted_at IS NULL
  UNION ALL
  SELECT c.id
  FROM conversations c
  JOIN conv_with_link p ON c.parent_id = p.conv_id
  WHERE c.org_id = ?1 AND c.deleted_at IS NULL
)
SELECT c.id, c.name
FROM conversations c
WHERE c.org_id = ?1
  AND c.type = 'channel'
  AND c.deleted_at IS NULL
  AND instr(lower(c.name), lower(?2)) > 0
  AND (
    EXISTS (
      SELECT 1 FROM conversation_members cm
      WHERE cm.conversation_id = c.id AND cm.user_id = ?3
    )
    OR (?4 = 1 AND c.id IN (SELECT conv_id FROM conv_with_link))
  )
ORDER BY c.name ASC
LIMIT ?5
`

type SearchChannelsParams struct {
	OrgID                string
	Query                string
	UserID               string
	IncludeProjectLinked interface{}
	Limit                int64
}

type SearchChannelsRow struct {
	ID   string
	Name string
}

func (q *Queries) SearchChannels(ctx context.Context, arg SearchChannelsParams) ([]SearchChannelsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchChannels,
		arg.OrgID,
		arg.Query,
		arg.UserID,
		arg.IncludeProjectLinked,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchChannelsRow
	for rows.Next() {
		var i SearchChannelsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDirectMessages = `-- name: SearchDirectMessages :many
SELECT c.id, u.name AS partner_name
FROM conversations c
JOIN conversation_members me ON me.conversation_id = c.id AND me.user_id = ?1
JOIN conversation_members cm ON cm.conversation_id = c.id AND cm.user_id != ?1
JOIN users u ON u.id = cm.user_id
WHERE c.org_id = ?2
  AND c.type = 'direct'
  AND (
    instr(lower(u.name), lower(?3)) > 0
    OR EXISTS (
      SELECT 1 FROM conversation_members cm2
      JOIN users u2 ON u2.id = cm2.user_id
      WHERE cm2.conversation_id = c.id AND instr(lower(u2.name), lower(?3)) > 0
    )
  )
ORDER BY u.name ASC
LIMIT ?4
`

type SearchDirectMessagesParams struct {
	UserID string
	OrgID  string
	Query  string
	Limit  int64
}

type SearchDirectMessagesRow struct {
	ID          string
	PartnerName string
}

// DM search only returns conversations the caller is a member of; the
// partner join is for the display name, not for discovery.
func (q *Queries) SearchDirectMessages(ctx context.Context, arg SearchDirectMessagesParams) ([]SearchDirectMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchDirectMessages,
		arg.UserID,
		arg.OrgID,
		arg.Query,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchDirectMessagesRow
	for rows.Next() {
		var i SearchDirectMessagesRow
		if err := rows.Scan(&i.ID, &i.PartnerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMembers = `-- name: SearchMembers :many
SELECT id, name, avatar_url
FROM users
WHERE org_id = ?1
  AND instr(lower(name), lower(?2)) > 0
ORDER BY name ASC
LIMIT ?3
`

type SearchMembersParams struct {
	OrgID string
	Query string
	Limit int64
}

type SearchMembersRow struct {
	ID        string
	Name      string
	AvatarUrl *string
}

func (q *Queries) SearchMembers(ctx context.Context, arg SearchMembersParams) ([]SearchMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMembers, arg.OrgID, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMembersRow
	for rows.Next() {
		var i SearchMembersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjects = `-- name: SearchProjects :many
SELECT p.id, p.name, p.slug, p.color
FROM projects_fts f
JOIN projects p ON p.id = f.project_id
WHERE f.org_id = ?1
  AND f.name MATCH ?2
  AND (?3 IS NULL OR p.id = ?3)
ORDER BY p.name ASC
LIMIT ?4
`

type SearchProjectsParams struct {
	OrgID     string
	Query     string
	ProjectID interface{}
	Limit     int64
}

type SearchProjectsRow struct {
	ID    string
	Name  string
	Slug  string
	Color string
}

func (q *Queries) SearchProjects(ctx context.Context, arg SearchProjectsParams) ([]SearchProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProjects,
		arg.OrgID,
		arg.Query,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProjectsRow
	for rows.Next() {
		var i SearchProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectsForUser = `-- name: SearchProjectsForUser :many
SELECT p.id, p.name, p.slug, p.color
FROM projects_fts f
JOIN projects p ON p.id = f.project_id AND p.org_id = ?1
JOIN project_members pm ON pm.project_id = p.id AND pm.user_id = ?2
WHERE f.org_id = ?1
  AND f.name MATCH ?3
ORDER BY p.name ASC
LIMIT ?4
`

type SearchProjectsForUserParams struct {
	OrgID  string
	UserID string
	Query  string
	Limit  int64
}

type SearchProjectsForUserRow struct {
	ID    string
	Name  string
	Slug  string
	Color string
}

// Project search scoped to projects the caller is an explicit member of.
// Used for viewer/guest users so they only discover projects they can access.
func (q *Queries) SearchProjectsForUser(ctx context.Context, arg SearchProjectsForUserParams) ([]SearchProjectsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchProjectsForUser,
		arg.OrgID,
		arg.UserID,
		arg.Query,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProjectsForUserRow
	for rows.Next() {
		var i SearchProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasks = `-- name: SearchTasks :many
SELECT t.id, t.title, t.project_id, p.name AS project_name, p.slug AS project_slug, p.color AS project_color
FROM tasks_fts f
JOIN tasks t ON t.id = f.task_id
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
WHERE f.org_id = ?1
  AND f.title MATCH ?2
  AND (?3 IS NULL OR t.project_id = ?3)
ORDER BY t.title ASC
LIMIT ?4
`

type SearchTasksParams struct {
	OrgID     string
	Query     string
	ProjectID interface{}
	Limit     int64
}

type SearchTasksRow struct {
	ID           string
	Title        string
	ProjectID    string
	ProjectName  string
	ProjectSlug  string
	ProjectColor string
}

func (q *Queries) SearchTasks(ctx context.Context, arg SearchTasksParams) ([]SearchTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTasks,
		arg.OrgID,
		arg.Query,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTasksRow
	for rows.Next() {
		var i SearchTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.ProjectColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTasksForUser = `-- name: SearchTasksForUser :many
SELECT t.id, t.title, t.project_id, p.name AS project_name, p.slug AS project_slug, p.color AS project_color
FROM tasks t
JOIN projects p ON p.id = t.project_id AND p.org_id = ?1
JOIN project_members pm ON pm.project_id = t.project_id AND pm.user_id = ?2
WHERE t.org_id = ?1
  AND t.id IN (SELECT task_id FROM tasks_fts WHERE tasks_fts.title MATCH ?3)
  AND (?4 IS NULL OR t.project_id = ?4)
ORDER BY t.title ASC
LIMIT ?5
`

type SearchTasksForUserParams struct {
	OrgID     string
	UserID    string
	Query     string
	ProjectID interface{}
	Limit     int64
}

type SearchTasksForUserRow struct {
	ID           string
	Title        string
	ProjectID    string
	ProjectName  string
	ProjectSlug  string
	ProjectColor string
}

// Task search scoped to projects the caller is an explicit member of. Used
// for viewer/guest users (project-scoped roles) so they only discover tasks in
// projects they can access. Elevated org roles (owner/admin/member) use the
// org-wide SearchTasks query instead.
func (q *Queries) SearchTasksForUser(ctx context.Context, arg SearchTasksForUserParams) ([]SearchTasksForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, searchTasksForUser,
		arg.OrgID,
		arg.UserID,
		arg.Query,
		arg.ProjectID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTasksForUserRow
	for rows.Next() {
		var i SearchTasksForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.ProjectColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
