// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, org_id, role, expires_at, user_agent, ip_address)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string
	UserID    string
	OrgID     string
	Role      string
	ExpiresAt string
	UserAgent *string
	IpAddress *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.Role,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, org_id, role, expires_at, revoked_at, created_at, user_agent, ip_address
FROM sessions
WHERE id = ?
`

type GetSessionByIDRow struct {
	ID        string
	UserID    string
	OrgID     string
	Role      string
	ExpiresAt string
	RevokedAt *string
	CreatedAt string
	UserAgent *string
	IpAddress *string
}

func (q *Queries) GetSessionByID(ctx context.Context, id string) (GetSessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, user_id, org_id, role, expires_at, revoked_at, created_at, user_agent, ip_address
FROM sessions
WHERE user_id = ? AND expires_at > datetime('now')
ORDER BY created_at DESC
`

type ListSessionsByUserRow struct {
	ID        string
	UserID    string
	OrgID     string
	Role      string
	ExpiresAt string
	RevokedAt *string
	CreatedAt string
	UserAgent *string
	IpAddress *string
}

// Active + revoked sessions for the user, most recent first. Expired rows
// are excluded so the list only shows sessions that could still be valid
// (or were explicitly revoked within their lifetime).
func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]ListSessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsByUserRow
	for rows.Next() {
		var i ListSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrgID,
			&i.Role,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UserAgent,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = datetime('now') WHERE id = ?
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, revokeSession, id)
	return err
}
