// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_dependencies.sql

package sqlc

import (
	"context"
)

const addTaskDependency = `-- name: AddTaskDependency :exec
INSERT INTO task_dependencies (task_id, blocks_task_id)
VALUES (?, ?)
`

type AddTaskDependencyParams struct {
	TaskID       string
	BlocksTaskID string
}

func (q *Queries) AddTaskDependency(ctx context.Context, arg AddTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, addTaskDependency, arg.TaskID, arg.BlocksTaskID)
	return err
}

const listBlockedTasks = `-- name: ListBlockedTasks :many
SELECT t.id, t.org_id, t.project_id, t.cycle_id, t.parent_task_id, t.created_by,
       t.title, t.description, t.status_id, t.priority, t.position_key,
       t.estimate, t.started_at, t.due_at, t.completed_at, t.created_at, t.updated_at
FROM task_dependencies d
JOIN tasks t ON t.id = d.task_id
WHERE d.blocks_task_id = ?
ORDER BY t.title ASC
`

type ListBlockedTasksRow struct {
	ID           string
	OrgID        string
	ProjectID    string
	CycleID      *string
	ParentTaskID *string
	CreatedBy    string
	Title        string
	Description  string
	StatusID     string
	Priority     string
	PositionKey  string
	Estimate     *int64
	StartedAt    *string
	DueAt        *string
	CompletedAt  *string
	CreatedAt    string
	UpdatedAt    string
}

// Tasks that the given task is blocking (these wait on the given task).
func (q *Queries) ListBlockedTasks(ctx context.Context, blocksTaskID string) ([]ListBlockedTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedTasks, blocksTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedTasksRow
	for rows.Next() {
		var i ListBlockedTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockingTasks = `-- name: ListBlockingTasks :many
SELECT t.id, t.org_id, t.project_id, t.cycle_id, t.parent_task_id, t.created_by,
       t.title, t.description, t.status_id, t.priority, t.position_key,
       t.estimate, t.started_at, t.due_at, t.completed_at, t.created_at, t.updated_at
FROM task_dependencies d
JOIN tasks t ON t.id = d.blocks_task_id
WHERE d.task_id = ?
ORDER BY t.title ASC
`

type ListBlockingTasksRow struct {
	ID           string
	OrgID        string
	ProjectID    string
	CycleID      *string
	ParentTaskID *string
	CreatedBy    string
	Title        string
	Description  string
	StatusID     string
	Priority     string
	PositionKey  string
	Estimate     *int64
	StartedAt    *string
	DueAt        *string
	CompletedAt  *string
	CreatedAt    string
	UpdatedAt    string
}

// Tasks that block the given task (the given task is blocked by these).
func (q *Queries) ListBlockingTasks(ctx context.Context, taskID string) ([]ListBlockingTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listBlockingTasks, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockingTasksRow
	for rows.Next() {
		var i ListBlockingTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTaskDependency = `-- name: RemoveTaskDependency :exec
DELETE FROM task_dependencies
WHERE task_id = ? AND blocks_task_id = ?
`

type RemoveTaskDependencyParams struct {
	TaskID       string
	BlocksTaskID string
}

func (q *Queries) RemoveTaskDependency(ctx context.Context, arg RemoveTaskDependencyParams) error {
	_, err := q.db.ExecContext(ctx, removeTaskDependency, arg.TaskID, arg.BlocksTaskID)
	return err
}
