// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_statuses.sql

package sqlc

import (
	"context"
)

const countTasksByStatus = `-- name: CountTasksByStatus :one
SELECT COUNT(*) FROM tasks WHERE status_id = ? AND project_id = ?
`

type CountTasksByStatusParams struct {
	StatusID  string
	ProjectID string
}

func (q *Queries) CountTasksByStatus(ctx context.Context, arg CountTasksByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByStatus, arg.StatusID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatus = `-- name: CreateStatus :exec
INSERT INTO task_statuses (id, project_id, name, color, position, category, is_default)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateStatusParams struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
	Position  int64
	Category  string
	IsDefault bool
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) error {
	_, err := q.db.ExecContext(ctx, createStatus,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.Category,
		arg.IsDefault,
	)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM task_statuses
WHERE id = ? AND project_id = ?
`

type DeleteStatusParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteStatus(ctx context.Context, arg DeleteStatusParams) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, arg.ID, arg.ProjectID)
	return err
}

const getMaxStatusPosition = `-- name: GetMaxStatusPosition :one
SELECT COALESCE(MAX(position), -1) FROM task_statuses WHERE project_id = ?
`

func (q *Queries) GetMaxStatusPosition(ctx context.Context, projectID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxStatusPosition, projectID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getStatusByID = `-- name: GetStatusByID :one
SELECT id, project_id, name, color, position, category, is_default
FROM task_statuses
WHERE id = ?
`

func (q *Queries) GetStatusByID(ctx context.Context, id string) (TaskStatus, error) {
	row := q.db.QueryRowContext(ctx, getStatusByID, id)
	var i TaskStatus
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.Category,
		&i.IsDefault,
	)
	return i, err
}

const listStatusesByProject = `-- name: ListStatusesByProject :many
SELECT id, project_id, name, color, position, category, is_default
FROM task_statuses
WHERE project_id = ?
ORDER BY position ASC
`

func (q *Queries) ListStatusesByProject(ctx context.Context, projectID string) ([]TaskStatus, error) {
	rows, err := q.db.QueryContext(ctx, listStatusesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskStatus
	for rows.Next() {
		var i TaskStatus
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.Category,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignTasksOnStatusDelete = `-- name: ReassignTasksOnStatusDelete :exec
UPDATE tasks
SET status_id = ?1
WHERE status_id = ?2 AND project_id = ?3
`

type ReassignTasksOnStatusDeleteParams struct {
	NewStatusID string
	OldStatusID string
	ProjectID   string
}

func (q *Queries) ReassignTasksOnStatusDelete(ctx context.Context, arg ReassignTasksOnStatusDeleteParams) error {
	_, err := q.db.ExecContext(ctx, reassignTasksOnStatusDelete, arg.NewStatusID, arg.OldStatusID, arg.ProjectID)
	return err
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE task_statuses
SET name = ?, color = ?, position = ?, category = ?
WHERE id = ? AND project_id = ?
`

type UpdateStatusParams struct {
	Name      string
	Color     string
	Position  int64
	Category  string
	ID        string
	ProjectID string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateStatus,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.Category,
		arg.ID,
		arg.ProjectID,
	)
	return err
}
