// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_activity.sql

package sqlc

import (
	"context"
)

const createTaskActivity = `-- name: CreateTaskActivity :exec
INSERT INTO task_activity (id, task_id, org_id, project_id, actor_id, action, field, old_value, new_value)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskActivityParams struct {
	ID        string
	TaskID    string
	OrgID     string
	ProjectID string
	ActorID   string
	Action    string
	Field     string
	OldValue  string
	NewValue  string
}

func (q *Queries) CreateTaskActivity(ctx context.Context, arg CreateTaskActivityParams) error {
	_, err := q.db.ExecContext(ctx, createTaskActivity,
		arg.ID,
		arg.TaskID,
		arg.OrgID,
		arg.ProjectID,
		arg.ActorID,
		arg.Action,
		arg.Field,
		arg.OldValue,
		arg.NewValue,
	)
	return err
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT ta.id, ta.task_id, ta.org_id, ta.project_id, ta.actor_id, ta.action,
       ta.field, ta.old_value, ta.new_value, ta.created_at,
       u.name AS actor_name, u.email AS actor_email
FROM task_activity ta
JOIN users u ON u.id = ta.actor_id
WHERE ta.task_id = ?1
  AND (
    (?2 = '' AND ?3 = '')
    OR (ta.created_at < ?2)
    OR (ta.created_at = ?2 AND ta.id < ?3)
  )
ORDER BY ta.created_at DESC, ta.id DESC
LIMIT ?4
`

type ListTaskActivityParams struct {
	TaskID          string
	CursorCreatedAt interface{}
	CursorID        interface{}
	LimitVal        int64
}

type ListTaskActivityRow struct {
	ID         string
	TaskID     string
	OrgID      string
	ProjectID  string
	ActorID    string
	Action     string
	Field      string
	OldValue   string
	NewValue   string
	CreatedAt  string
	ActorName  string
	ActorEmail string
}

func (q *Queries) ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]ListTaskActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listTaskActivity,
		arg.TaskID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTaskActivityRow
	for rows.Next() {
		var i ListTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.OrgID,
			&i.ProjectID,
			&i.ActorID,
			&i.Action,
			&i.Field,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
