// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"
	"strings"
)

const countSubtasksByParent = `-- name: CountSubtasksByParent :one
SELECT COUNT(*) FROM tasks WHERE parent_task_id = ? AND org_id = ?
`

type CountSubtasksByParentParams struct {
	ParentTaskID *string
	OrgID        string
}

// Returns the number of direct children of a task. Used by the delete handler
// to decide whether to block (409) when no mode is specified.
func (q *Queries) CountSubtasksByParent(ctx context.Context, arg CountSubtasksByParentParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSubtasksByParent, arg.ParentTaskID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByUser = `-- name: CountTasksByUser :one
SELECT COUNT(*)
FROM tasks t
JOIN task_assignees ta ON ta.task_id = t.id AND ta.user_id = ?1
WHERE t.org_id = ?2
  AND (?3 IS NULL OR t.status_id = ?3)
  AND (t.priority = ?4 OR ?4 = '')
  AND (?5 = 1 OR t.completed_at IS NULL)
  AND (
    ?6 IS NULL
    OR (?6 = '__backlog__' AND t.cycle_id IS NULL)
    OR (t.cycle_id = ?6)
  )
  AND (instr(lower(t.title), lower(?7)) > 0 OR ?7 = '%%')
`

type CountTasksByUserParams struct {
	UserID        string
	OrgID         string
	StatusID      interface{}
	Priority      string
	ShowCompleted interface{}
	CycleID       interface{}
	Search        string
}

func (q *Queries) CountTasksByUser(ctx context.Context, arg CountTasksByUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTasksByUser,
		arg.UserID,
		arg.OrgID,
		arg.StatusID,
		arg.Priority,
		arg.ShowCompleted,
		arg.CycleID,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, org_id, project_id, cycle_id, parent_task_id, created_by, title, description, status_id, priority, position_key, subtask_position, estimate, started_at, due_at, completed_at, template_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID              string
	OrgID           string
	ProjectID       string
	CycleID         *string
	ParentTaskID    *string
	CreatedBy       string
	Title           string
	Description     string
	StatusID        string
	Priority        string
	PositionKey     string
	SubtaskPosition *string
	Estimate        *int64
	StartedAt       *string
	DueAt           *string
	CompletedAt     *string
	TemplateID      *string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.CycleID,
		arg.ParentTaskID,
		arg.CreatedBy,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.PositionKey,
		arg.SubtaskPosition,
		arg.Estimate,
		arg.StartedAt,
		arg.DueAt,
		arg.CompletedAt,
		arg.TemplateID,
	)
	return err
}

const deleteSubtasksByParent = `-- name: DeleteSubtasksByParent :exec
DELETE FROM tasks
WHERE parent_task_id = ? AND org_id = ?
`

type DeleteSubtasksByParentParams struct {
	ParentTaskID *string
	OrgID        string
}

// Deletes all direct children of a task (1-level nesting enforced by the
// service, so no recursion needed). Used by cascade-delete.
func (q *Queries) DeleteSubtasksByParent(ctx context.Context, arg DeleteSubtasksByParentParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubtasksByParent, arg.ParentTaskID, arg.OrgID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = ? AND project_id = ? AND org_id = ?
`

type DeleteTaskParams struct {
	ID        string
	ProjectID string
	OrgID     string
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.ProjectID, arg.OrgID)
	return err
}

const getLastPositionKey = `-- name: GetLastPositionKey :one
SELECT COALESCE(MAX(position_key), '') FROM tasks WHERE project_id = ? AND status_id = ? AND org_id = ?
`

type GetLastPositionKeyParams struct {
	ProjectID string
	StatusID  string
	OrgID     string
}

func (q *Queries) GetLastPositionKey(ctx context.Context, arg GetLastPositionKeyParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastPositionKey, arg.ProjectID, arg.StatusID, arg.OrgID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getLastSubtaskPosition = `-- name: GetLastSubtaskPosition :one
SELECT COALESCE(MAX(subtask_position), '') FROM tasks WHERE parent_task_id = ? AND org_id = ?
`

type GetLastSubtaskPositionParams struct {
	ParentTaskID *string
	OrgID        string
}

// Returns the highest subtask_position among a task's children, or ” if none.
// Used to generate a new lexorank key at the end when creating/reordering.
func (q *Queries) GetLastSubtaskPosition(ctx context.Context, arg GetLastSubtaskPositionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLastSubtaskPosition, arg.ParentTaskID, arg.OrgID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getPositionKeyNeighbors = `-- name: GetPositionKeyNeighbors :one
SELECT
  COALESCE(
    (SELECT position_key FROM tasks t2
     WHERE t2.project_id = tasks.project_id
       AND t2.status_id  = tasks.status_id
       AND t2.position_key < tasks.position_key
     ORDER BY t2.position_key DESC LIMIT 1),
    ''
  ) AS prev_key,
  COALESCE(
    (SELECT position_key FROM tasks t3
     WHERE t3.project_id = tasks.project_id
       AND t3.status_id  = tasks.status_id
       AND t3.position_key > tasks.position_key
     ORDER BY t3.position_key ASC LIMIT 1),
    ''
  ) AS next_key
FROM tasks WHERE tasks.id = ? AND tasks.org_id = ? LIMIT 1
`

type GetPositionKeyNeighborsParams struct {
	ID    string
	OrgID string
}

type GetPositionKeyNeighborsRow struct {
	PrevKey interface{}
	NextKey interface{}
}

func (q *Queries) GetPositionKeyNeighbors(ctx context.Context, arg GetPositionKeyNeighborsParams) (GetPositionKeyNeighborsRow, error) {
	row := q.db.QueryRowContext(ctx, getPositionKeyNeighbors, arg.ID, arg.OrgID)
	var i GetPositionKeyNeighborsRow
	err := row.Scan(&i.PrevKey, &i.NextKey)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.org_id, t.project_id, t.cycle_id, t.parent_task_id, t.created_by, t.title, t.description, t.status_id, t.priority, t.position_key, t.subtask_position, t.estimate, t.started_at, t.due_at, t.completed_at, t.template_id, t.created_at, t.updated_at,
  (SELECT COUNT(*) FROM tasks c WHERE c.parent_task_id = t.id) AS subtask_count,
  (SELECT COUNT(*) FROM tasks c WHERE c.parent_task_id = t.id AND c.completed_at IS NOT NULL) AS completed_subtask_count,
  p.title AS parent_title
FROM tasks t
LEFT JOIN tasks p ON p.id = t.parent_task_id
WHERE t.id = ? AND t.project_id = ? AND t.org_id = ?
`

type GetTaskByIDParams struct {
	ID        string
	ProjectID string
	OrgID     string
}

type GetTaskByIDRow struct {
	ID                    string
	OrgID                 string
	ProjectID             string
	CycleID               *string
	ParentTaskID          *string
	CreatedBy             string
	Title                 string
	Description           string
	StatusID              string
	Priority              string
	PositionKey           string
	SubtaskPosition       *string
	Estimate              *int64
	StartedAt             *string
	DueAt                 *string
	CompletedAt           *string
	TemplateID            *string
	CreatedAt             string
	UpdatedAt             string
	SubtaskCount          int64
	CompletedSubtaskCount int64
	ParentTitle           *string
}

func (q *Queries) GetTaskByID(ctx context.Context, arg GetTaskByIDParams) (GetTaskByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, arg.ID, arg.ProjectID, arg.OrgID)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.CycleID,
		&i.ParentTaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.PositionKey,
		&i.SubtaskPosition,
		&i.Estimate,
		&i.StartedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubtaskCount,
		&i.CompletedSubtaskCount,
		&i.ParentTitle,
	)
	return i, err
}

const getTaskByIDAndOrg = `-- name: GetTaskByIDAndOrg :one
SELECT id, org_id, project_id, cycle_id, parent_task_id, created_by, title, description, status_id, priority, position_key, estimate, started_at, due_at, completed_at, template_id, created_at, updated_at
FROM tasks
WHERE id = ?1 AND org_id = ?2
`

type GetTaskByIDAndOrgParams struct {
	ID    string
	OrgID string
}

type GetTaskByIDAndOrgRow struct {
	ID           string
	OrgID        string
	ProjectID    string
	CycleID      *string
	ParentTaskID *string
	CreatedBy    string
	Title        string
	Description  string
	StatusID     string
	Priority     string
	PositionKey  string
	Estimate     *int64
	StartedAt    *string
	DueAt        *string
	CompletedAt  *string
	TemplateID   *string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) GetTaskByIDAndOrg(ctx context.Context, arg GetTaskByIDAndOrgParams) (GetTaskByIDAndOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getTaskByIDAndOrg, arg.ID, arg.OrgID)
	var i GetTaskByIDAndOrgRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.CycleID,
		&i.ParentTaskID,
		&i.CreatedBy,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.PositionKey,
		&i.Estimate,
		&i.StartedAt,
		&i.DueAt,
		&i.CompletedAt,
		&i.TemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByIDsFull = `-- name: GetTasksByIDsFull :many
SELECT id, org_id, project_id, cycle_id, parent_task_id, created_by, title,
       description, status_id, priority, estimate, position_key, subtask_position,
       template_id, started_at, due_at, completed_at, created_at, updated_at
FROM tasks
WHERE org_id = ?1 AND id IN (/*SLICE:ids*/?)
`

type GetTasksByIDsFullParams struct {
	OrgID string
	Ids   []string
}

// Full-projection batch fetch by IDs (org-scoped). Used by BatchUpdate which
// needs complete task rows to update safely (priority/status/etc.). The
// mention-hydration query GetTasksByIDs (mentions.sql) is intentionally
// minimal; this is the full version for mutation paths.
func (q *Queries) GetTasksByIDsFull(ctx context.Context, arg GetTasksByIDsFullParams) ([]Task, error) {
	query := getTasksByIDsFull
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrgID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.Estimate,
			&i.PositionKey,
			&i.SubtaskPosition,
			&i.TemplateID,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubtasks = `-- name: ListSubtasks :many
SELECT id, org_id, project_id, cycle_id, parent_task_id, created_by, title, description, status_id, priority, position_key, subtask_position, estimate, started_at, due_at, completed_at, template_id, created_at, updated_at
FROM tasks
WHERE parent_task_id = ? AND org_id = ?
ORDER BY subtask_position ASC
`

type ListSubtasksParams struct {
	ParentTaskID *string
	OrgID        string
}

type ListSubtasksRow struct {
	ID              string
	OrgID           string
	ProjectID       string
	CycleID         *string
	ParentTaskID    *string
	CreatedBy       string
	Title           string
	Description     string
	StatusID        string
	Priority        string
	PositionKey     string
	SubtaskPosition *string
	Estimate        *int64
	StartedAt       *string
	DueAt           *string
	CompletedAt     *string
	TemplateID      *string
	CreatedAt       string
	UpdatedAt       string
}

// Direct children of a task (one level deep). Ordered by subtask_position
// (parent-scoped lexorank). Used by MoveToProject to recursively move
// subtasks along with their parent, and by the dedicated
// GET /tasks/{taskId}/subtasks endpoint.
func (q *Queries) ListSubtasks(ctx context.Context, arg ListSubtasksParams) ([]ListSubtasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSubtasks, arg.ParentTaskID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubtasksRow
	for rows.Next() {
		var i ListSubtasksRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.SubtaskPosition,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByCycle = `-- name: ListTasksByCycle :many
SELECT id, org_id, project_id, cycle_id, parent_task_id, created_by, title, description, status_id, priority, position_key, estimate, started_at, due_at, completed_at, template_id, created_at, updated_at
FROM tasks
WHERE cycle_id = ?1 AND org_id = ?2
ORDER BY position_key ASC
`

type ListTasksByCycleParams struct {
	CycleID *string
	OrgID   string
}

type ListTasksByCycleRow struct {
	ID           string
	OrgID        string
	ProjectID    string
	CycleID      *string
	ParentTaskID *string
	CreatedBy    string
	Title        string
	Description  string
	StatusID     string
	Priority     string
	PositionKey  string
	Estimate     *int64
	StartedAt    *string
	DueAt        *string
	CompletedAt  *string
	TemplateID   *string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) ListTasksByCycle(ctx context.Context, arg ListTasksByCycleParams) ([]ListTasksByCycleRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByCycle, arg.CycleID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByCycleRow
	for rows.Next() {
		var i ListTasksByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT t.id, t.org_id, t.project_id, t.cycle_id, t.parent_task_id, t.created_by, t.title, t.description, t.status_id, t.priority, t.position_key, t.estimate, t.started_at, t.due_at, t.completed_at, t.template_id, t.created_at, t.updated_at,
  (SELECT COUNT(*) FROM tasks c WHERE c.parent_task_id = t.id) AS subtask_count,
  (SELECT COUNT(*) FROM tasks c WHERE c.parent_task_id = t.id AND c.completed_at IS NOT NULL) AS completed_subtask_count
FROM tasks t
WHERE t.project_id = ?1
  AND t.org_id = ?2
  AND (?3 = 1 OR t.parent_task_id IS NULL)
  AND (?4 IS NULL OR t.status_id = ?4)
  AND (
    ?5 IS NULL
    OR (?5 = '__backlog__' AND t.cycle_id IS NULL)
    OR (t.cycle_id = ?5)
  )
  AND (?6 IS NULL OR EXISTS (SELECT 1 FROM task_assignees WHERE task_assignees.task_id = t.id AND task_assignees.user_id = ?6))
  AND (t.priority = ?7 OR ?7 = '')
  AND (instr(lower(t.title), lower(?8)) > 0 OR ?8 = '%%')
  AND (?9 = 0 OR EXISTS (
    SELECT 1 FROM task_labels tl
    WHERE tl.task_id = t.id AND tl.label_id IN (/*SLICE:label_ids*/?)
  ))
ORDER BY t.position_key ASC
`

type ListTasksByProjectParams struct {
	ProjectID       string
	OrgID           string
	IncludeSubtasks interface{}
	StatusID        interface{}
	CycleID         interface{}
	AssigneeID      interface{}
	Priority        string
	Search          string
	HasLabelFilter  interface{}
	LabelIds        []string
}

type ListTasksByProjectRow struct {
	ID                    string
	OrgID                 string
	ProjectID             string
	CycleID               *string
	ParentTaskID          *string
	CreatedBy             string
	Title                 string
	Description           string
	StatusID              string
	Priority              string
	PositionKey           string
	Estimate              *int64
	StartedAt             *string
	DueAt                 *string
	CompletedAt           *string
	TemplateID            *string
	CreatedAt             string
	UpdatedAt             string
	SubtaskCount          int64
	CompletedSubtaskCount int64
}

func (q *Queries) ListTasksByProject(ctx context.Context, arg ListTasksByProjectParams) ([]ListTasksByProjectRow, error) {
	query := listTasksByProject
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	queryParams = append(queryParams, arg.OrgID)
	queryParams = append(queryParams, arg.IncludeSubtasks)
	queryParams = append(queryParams, arg.StatusID)
	queryParams = append(queryParams, arg.CycleID)
	queryParams = append(queryParams, arg.AssigneeID)
	queryParams = append(queryParams, arg.Priority)
	queryParams = append(queryParams, arg.Search)
	queryParams = append(queryParams, arg.HasLabelFilter)
	if len(arg.LabelIds) > 0 {
		for _, v := range arg.LabelIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:label_ids*/?", strings.Repeat(",?", len(arg.LabelIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:label_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByProjectRow
	for rows.Next() {
		var i ListTasksByProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubtaskCount,
			&i.CompletedSubtaskCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByUser = `-- name: ListTasksByUser :many
SELECT t.id, t.org_id, t.project_id, t.cycle_id, t.parent_task_id, t.created_by,
       t.title, t.description, t.status_id, t.priority, t.position_key,
       t.estimate, t.started_at, t.due_at, t.completed_at, t.template_id, t.created_at, t.updated_at,
       p.name AS project_name, p.slug AS project_slug, p.color AS project_color,
       s.name AS status_name, s.color AS status_color
FROM tasks t
JOIN projects p ON p.id = t.project_id
JOIN task_statuses s ON s.id = t.status_id
WHERE t.org_id = ?1
  AND EXISTS (
    SELECT 1 FROM task_assignees ta
    WHERE ta.task_id = t.id AND ta.user_id = ?2
  )
  AND (?3 IS NULL OR t.status_id = ?3)
  AND (t.priority = ?4 OR ?4 = '')
  AND (?5 = 1 OR t.completed_at IS NULL)
  AND (
    ?6 IS NULL
    OR (?6 = '__backlog__' AND t.cycle_id IS NULL)
    OR (t.cycle_id = ?6)
  )
  AND (?7 = 0 OR EXISTS (
    SELECT 1 FROM task_labels tl
    WHERE tl.task_id = t.id AND tl.label_id IN (/*SLICE:label_ids*/?)
  ))
  AND (?9 = 0 OR EXISTS (
    SELECT 1 FROM project_members pm
    WHERE pm.project_id = t.project_id AND pm.user_id = ?2
  ))
  AND (instr(lower(t.title), lower(?10)) > 0 OR ?10 = '%%')
  AND (
    ?11 = ''
    OR t.updated_at < ?11
    OR (t.updated_at = ?11 AND t.id < ?12)
  )
ORDER BY t.updated_at DESC, t.id DESC
LIMIT ?13
`

type ListTasksByUserParams struct {
	OrgID                    string
	EffectiveAssigneeID      string
	StatusID                 interface{}
	Priority                 string
	ShowCompleted            interface{}
	CycleID                  interface{}
	HasLabelFilter           interface{}
	LabelIds                 []string
	RequireProjectMembership interface{}
	Search                   string
	CursorUpdatedAt          interface{}
	CursorID                 string
	LimitVal                 int64
}

type ListTasksByUserRow struct {
	ID           string
	OrgID        string
	ProjectID    string
	CycleID      *string
	ParentTaskID *string
	CreatedBy    string
	Title        string
	Description  string
	StatusID     string
	Priority     string
	PositionKey  string
	Estimate     *int64
	StartedAt    *string
	DueAt        *string
	CompletedAt  *string
	TemplateID   *string
	CreatedAt    string
	UpdatedAt    string
	ProjectName  string
	ProjectSlug  string
	ProjectColor string
	StatusName   string
	StatusColor  string
}

func (q *Queries) ListTasksByUser(ctx context.Context, arg ListTasksByUserParams) ([]ListTasksByUserRow, error) {
	query := listTasksByUser
	var queryParams []interface{}
	queryParams = append(queryParams, arg.OrgID)
	queryParams = append(queryParams, arg.EffectiveAssigneeID)
	queryParams = append(queryParams, arg.StatusID)
	queryParams = append(queryParams, arg.Priority)
	queryParams = append(queryParams, arg.ShowCompleted)
	queryParams = append(queryParams, arg.CycleID)
	queryParams = append(queryParams, arg.HasLabelFilter)
	if len(arg.LabelIds) > 0 {
		for _, v := range arg.LabelIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:label_ids*/?", strings.Repeat(",?", len(arg.LabelIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:label_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.RequireProjectMembership)
	queryParams = append(queryParams, arg.Search)
	queryParams = append(queryParams, arg.CursorUpdatedAt)
	queryParams = append(queryParams, arg.CursorID)
	queryParams = append(queryParams, arg.LimitVal)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTasksByUserRow
	for rows.Next() {
		var i ListTasksByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CycleID,
			&i.ParentTaskID,
			&i.CreatedBy,
			&i.Title,
			&i.Description,
			&i.StatusID,
			&i.Priority,
			&i.PositionKey,
			&i.Estimate,
			&i.StartedAt,
			&i.DueAt,
			&i.CompletedAt,
			&i.TemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProjectName,
			&i.ProjectSlug,
			&i.ProjectColor,
			&i.StatusName,
			&i.StatusColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveIncompleteTasksToCycle = `-- name: MoveIncompleteTasksToCycle :exec
UPDATE tasks SET cycle_id = ?1, updated_at = datetime('now') WHERE cycle_id = ?2 AND org_id = ?3 AND completed_at IS NULL
`

type MoveIncompleteTasksToCycleParams struct {
	ToCycleID   *string
	FromCycleID *string
	OrgID       string
}

func (q *Queries) MoveIncompleteTasksToCycle(ctx context.Context, arg MoveIncompleteTasksToCycleParams) error {
	_, err := q.db.ExecContext(ctx, moveIncompleteTasksToCycle, arg.ToCycleID, arg.FromCycleID, arg.OrgID)
	return err
}

const moveTaskToProject = `-- name: MoveTaskToProject :exec
UPDATE tasks
SET project_id = ?, status_id = ?, cycle_id = NULL, parent_task_id = NULL,
    position_key = ?, completed_at = ?, updated_at = datetime('now')
WHERE id = ? AND project_id = ? AND org_id = ?
`

type MoveTaskToProjectParams struct {
	ProjectID   string
	StatusID    string
	PositionKey string
	CompletedAt *string
	ID          string
	ProjectID_2 string
	OrgID       string
}

// Re-homes a task into a different project + status. Caller must validate
// the target project/status belong to the org first. Clears cycle_id (cycles
// are project-scoped) and parent_task_id (parent may not exist in the target
// project). completed_at is passed explicitly so it stays in sync with the
// target status category.
func (q *Queries) MoveTaskToProject(ctx context.Context, arg MoveTaskToProjectParams) error {
	_, err := q.db.ExecContext(ctx, moveTaskToProject,
		arg.ProjectID,
		arg.StatusID,
		arg.PositionKey,
		arg.CompletedAt,
		arg.ID,
		arg.ProjectID_2,
		arg.OrgID,
	)
	return err
}

const moveTasksToCycle = `-- name: MoveTasksToCycle :exec
UPDATE tasks SET cycle_id = ?1, updated_at = datetime('now') WHERE cycle_id = ?2 AND org_id = ?3
`

type MoveTasksToCycleParams struct {
	ToCycleID   *string
	FromCycleID *string
	OrgID       string
}

func (q *Queries) MoveTasksToCycle(ctx context.Context, arg MoveTasksToCycleParams) error {
	_, err := q.db.ExecContext(ctx, moveTasksToCycle, arg.ToCycleID, arg.FromCycleID, arg.OrgID)
	return err
}

const promoteSubtasksByParent = `-- name: PromoteSubtasksByParent :exec
UPDATE tasks
SET parent_task_id = NULL, updated_at = datetime('now')
WHERE parent_task_id = ? AND org_id = ?
`

type PromoteSubtasksByParentParams struct {
	ParentTaskID *string
	OrgID        string
}

// Clears parent_task_id on all direct children so they become top-level
// tasks. Used by the promote delete mode.
func (q *Queries) PromoteSubtasksByParent(ctx context.Context, arg PromoteSubtasksByParentParams) error {
	_, err := q.db.ExecContext(ctx, promoteSubtasksByParent, arg.ParentTaskID, arg.OrgID)
	return err
}

const unassignCycleFromIncompleteTasks = `-- name: UnassignCycleFromIncompleteTasks :exec
UPDATE tasks SET cycle_id = NULL, updated_at = datetime('now') WHERE cycle_id = ?1 AND org_id = ?2 AND completed_at IS NULL
`

type UnassignCycleFromIncompleteTasksParams struct {
	CycleID *string
	OrgID   string
}

func (q *Queries) UnassignCycleFromIncompleteTasks(ctx context.Context, arg UnassignCycleFromIncompleteTasksParams) error {
	_, err := q.db.ExecContext(ctx, unassignCycleFromIncompleteTasks, arg.CycleID, arg.OrgID)
	return err
}

const unassignCycleFromTasks = `-- name: UnassignCycleFromTasks :exec
UPDATE tasks SET cycle_id = NULL, updated_at = datetime('now') WHERE cycle_id = ?1 AND org_id = ?2
`

type UnassignCycleFromTasksParams struct {
	CycleID *string
	OrgID   string
}

func (q *Queries) UnassignCycleFromTasks(ctx context.Context, arg UnassignCycleFromTasksParams) error {
	_, err := q.db.ExecContext(ctx, unassignCycleFromTasks, arg.CycleID, arg.OrgID)
	return err
}

const updateSubtaskPosition = `-- name: UpdateSubtaskPosition :exec
UPDATE tasks
SET subtask_position = ?, updated_at = datetime('now')
WHERE id = ? AND parent_task_id = ? AND org_id = ?
`

type UpdateSubtaskPositionParams struct {
	SubtaskPosition *string
	ID              string
	ParentTaskID    *string
	OrgID           string
}

// Sets the subtask_position (parent-scoped ordering) for a single subtask.
// Used by ReorderSubtasks to re-key children.
func (q *Queries) UpdateSubtaskPosition(ctx context.Context, arg UpdateSubtaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateSubtaskPosition,
		arg.SubtaskPosition,
		arg.ID,
		arg.ParentTaskID,
		arg.OrgID,
	)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = ?, description = ?, status_id = ?, priority = ?, cycle_id = ?, parent_task_id = ?, estimate = ?, started_at = ?, due_at = ?, completed_at = ?, position_key = ?, subtask_position = ?, updated_at = ?
WHERE id = ? AND project_id = ? AND org_id = ?
`

type UpdateTaskParams struct {
	Title           string
	Description     string
	StatusID        string
	Priority        string
	CycleID         *string
	ParentTaskID    *string
	Estimate        *int64
	StartedAt       *string
	DueAt           *string
	CompletedAt     *string
	PositionKey     string
	SubtaskPosition *string
	UpdatedAt       string
	ID              string
	ProjectID       string
	OrgID           string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.CycleID,
		arg.ParentTaskID,
		arg.Estimate,
		arg.StartedAt,
		arg.DueAt,
		arg.CompletedAt,
		arg.PositionKey,
		arg.SubtaskPosition,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
	)
	return err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks
SET status_id = ?, position_key = ?, updated_at = datetime('now')
WHERE id = ? AND project_id = ? AND org_id = ?
`

type UpdateTaskPositionParams struct {
	StatusID    string
	PositionKey string
	ID          string
	ProjectID   string
	OrgID       string
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition,
		arg.StatusID,
		arg.PositionKey,
		arg.ID,
		arg.ProjectID,
		arg.OrgID,
	)
	return err
}
