// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_templates.sql

package sqlc

import (
	"context"
)

const claimDueRecurringTemplate = `-- name: ClaimDueRecurringTemplate :execrows
UPDATE task_templates
SET next_run_at = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ? AND next_run_at = ?
`

type ClaimDueRecurringTemplateParams struct {
	NextRunAt   *string
	ID          string
	OrgID       string
	NextRunAt_2 *string
}

func (q *Queries) ClaimDueRecurringTemplate(ctx context.Context, arg ClaimDueRecurringTemplateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimDueRecurringTemplate,
		arg.NextRunAt,
		arg.ID,
		arg.OrgID,
		arg.NextRunAt_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const clearTemplateLastError = `-- name: ClearTemplateLastError :exec
UPDATE task_templates
SET last_error = NULL, last_error_at = NULL, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type ClearTemplateLastErrorParams struct {
	ID    string
	OrgID string
}

func (q *Queries) ClearTemplateLastError(ctx context.Context, arg ClearTemplateLastErrorParams) error {
	_, err := q.db.ExecContext(ctx, clearTemplateLastError, arg.ID, arg.OrgID)
	return err
}

const createTaskTemplate = `-- name: CreateTaskTemplate :exec
INSERT INTO task_templates (id, org_id, project_id, name, description, priority, status_id, assignee_ids, estimate, recurrence_pattern, recurrence_days, next_run_at, created_by)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskTemplateParams struct {
	ID                string
	OrgID             string
	ProjectID         string
	Name              string
	Description       string
	Priority          string
	StatusID          string
	AssigneeIds       string
	Estimate          *int64
	RecurrencePattern string
	RecurrenceDays    string
	NextRunAt         *string
	CreatedBy         string
}

func (q *Queries) CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) error {
	_, err := q.db.ExecContext(ctx, createTaskTemplate,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.StatusID,
		arg.AssigneeIds,
		arg.Estimate,
		arg.RecurrencePattern,
		arg.RecurrenceDays,
		arg.NextRunAt,
		arg.CreatedBy,
	)
	return err
}

const deleteTaskTemplate = `-- name: DeleteTaskTemplate :exec
DELETE FROM task_templates WHERE id = ? AND org_id = ?
`

type DeleteTaskTemplateParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteTaskTemplate(ctx context.Context, arg DeleteTaskTemplateParams) error {
	_, err := q.db.ExecContext(ctx, deleteTaskTemplate, arg.ID, arg.OrgID)
	return err
}

const getTaskTemplateByID = `-- name: GetTaskTemplateByID :one
SELECT id, org_id, project_id, name, description, priority, status_id, assignee_ids, estimate, recurrence_pattern, recurrence_days, next_run_at, last_error, last_error_at, created_by, created_at, updated_at
FROM task_templates
WHERE id = ? AND org_id = ?
`

type GetTaskTemplateByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetTaskTemplateByID(ctx context.Context, arg GetTaskTemplateByIDParams) (TaskTemplate, error) {
	row := q.db.QueryRowContext(ctx, getTaskTemplateByID, arg.ID, arg.OrgID)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.Priority,
		&i.StatusID,
		&i.AssigneeIds,
		&i.Estimate,
		&i.RecurrencePattern,
		&i.RecurrenceDays,
		&i.NextRunAt,
		&i.LastError,
		&i.LastErrorAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueRecurringTemplates = `-- name: ListDueRecurringTemplates :many
SELECT id, org_id, project_id, name, description, priority, status_id, assignee_ids, estimate, recurrence_pattern, recurrence_days, next_run_at, last_error, last_error_at, created_by, created_at, updated_at
FROM task_templates
WHERE recurrence_pattern != 'none'
  AND next_run_at IS NOT NULL
  AND next_run_at <= ?
ORDER BY next_run_at ASC
`

func (q *Queries) ListDueRecurringTemplates(ctx context.Context, nextRunAt *string) ([]TaskTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listDueRecurringTemplates, nextRunAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTemplate
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeIds,
			&i.Estimate,
			&i.RecurrencePattern,
			&i.RecurrenceDays,
			&i.NextRunAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTemplatesByOrg = `-- name: ListTaskTemplatesByOrg :many
SELECT id, org_id, project_id, name, description, priority, status_id, assignee_ids, estimate, recurrence_pattern, recurrence_days, next_run_at, last_error, last_error_at, created_by, created_at, updated_at
FROM task_templates
WHERE org_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListTaskTemplatesByOrg(ctx context.Context, orgID string) ([]TaskTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTaskTemplatesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTemplate
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeIds,
			&i.Estimate,
			&i.RecurrencePattern,
			&i.RecurrenceDays,
			&i.NextRunAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTemplatesByProject = `-- name: ListTaskTemplatesByProject :many
SELECT id, org_id, project_id, name, description, priority, status_id, assignee_ids, estimate, recurrence_pattern, recurrence_days, next_run_at, last_error, last_error_at, created_by, created_at, updated_at
FROM task_templates
WHERE project_id = ? AND org_id = ?
ORDER BY created_at DESC
`

type ListTaskTemplatesByProjectParams struct {
	ProjectID string
	OrgID     string
}

func (q *Queries) ListTaskTemplatesByProject(ctx context.Context, arg ListTaskTemplatesByProjectParams) ([]TaskTemplate, error) {
	rows, err := q.db.QueryContext(ctx, listTaskTemplatesByProject, arg.ProjectID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskTemplate
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.Name,
			&i.Description,
			&i.Priority,
			&i.StatusID,
			&i.AssigneeIds,
			&i.Estimate,
			&i.RecurrencePattern,
			&i.RecurrenceDays,
			&i.NextRunAt,
			&i.LastError,
			&i.LastErrorAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTemplateLastError = `-- name: SetTemplateLastError :exec
UPDATE task_templates
SET last_error = ?, last_error_at = datetime('now'), updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type SetTemplateLastErrorParams struct {
	LastError *string
	ID        string
	OrgID     string
}

func (q *Queries) SetTemplateLastError(ctx context.Context, arg SetTemplateLastErrorParams) error {
	_, err := q.db.ExecContext(ctx, setTemplateLastError, arg.LastError, arg.ID, arg.OrgID)
	return err
}

const updateTaskTemplate = `-- name: UpdateTaskTemplate :exec
UPDATE task_templates
SET name = ?, description = ?, priority = ?, status_id = ?, assignee_ids = ?, estimate = ?, recurrence_pattern = ?, recurrence_days = ?, next_run_at = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateTaskTemplateParams struct {
	Name              string
	Description       string
	Priority          string
	StatusID          string
	AssigneeIds       string
	Estimate          *int64
	RecurrencePattern string
	RecurrenceDays    string
	NextRunAt         *string
	ID                string
	OrgID             string
}

func (q *Queries) UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskTemplate,
		arg.Name,
		arg.Description,
		arg.Priority,
		arg.StatusID,
		arg.AssigneeIds,
		arg.Estimate,
		arg.RecurrencePattern,
		arg.RecurrenceDays,
		arg.NextRunAt,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateTaskTemplateNextRun = `-- name: UpdateTaskTemplateNextRun :exec
UPDATE task_templates
SET next_run_at = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateTaskTemplateNextRunParams struct {
	NextRunAt *string
	ID        string
	OrgID     string
}

func (q *Queries) UpdateTaskTemplateNextRun(ctx context.Context, arg UpdateTaskTemplateNextRunParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskTemplateNextRun, arg.NextRunAt, arg.ID, arg.OrgID)
	return err
}
