// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_assignees.sql

package sqlc

import (
	"context"
	"strings"
)

const addTaskAssignee = `-- name: AddTaskAssignee :exec
INSERT INTO task_assignees (task_id, user_id) VALUES (?, ?)
`

type AddTaskAssigneeParams struct {
	TaskID string
	UserID string
}

func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) error {
	_, err := q.db.ExecContext(ctx, addTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const listAssigneesByTaskIDs = `-- name: ListAssigneesByTaskIDs :many
SELECT ta.task_id, u.id, u.name, u.email, u.avatar_url
FROM task_assignees ta
JOIN users u ON u.id = ta.user_id
WHERE ta.task_id IN (/*SLICE:task_ids*/?)
`

type ListAssigneesByTaskIDsRow struct {
	TaskID    string
	ID        string
	Name      string
	Email     string
	AvatarUrl *string
}

func (q *Queries) ListAssigneesByTaskIDs(ctx context.Context, taskIds []string) ([]ListAssigneesByTaskIDsRow, error) {
	query := listAssigneesByTaskIDs
	var queryParams []interface{}
	if len(taskIds) > 0 {
		for _, v := range taskIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:task_ids*/?", strings.Repeat(",?", len(taskIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:task_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssigneesByTaskIDsRow
	for rows.Next() {
		var i ListAssigneesByTaskIDsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT task_id, user_id FROM task_assignees WHERE task_id = ?
`

func (q *Queries) ListTaskAssignees(ctx context.Context, taskID string) ([]TaskAssignee, error) {
	rows, err := q.db.QueryContext(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskAssignee
	for rows.Next() {
		var i TaskAssignee
		if err := rows.Scan(&i.TaskID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskAssignees = `-- name: SetTaskAssignees :exec
DELETE FROM task_assignees WHERE task_id = ?
`

func (q *Queries) SetTaskAssignees(ctx context.Context, taskID string) error {
	_, err := q.db.ExecContext(ctx, setTaskAssignees, taskID)
	return err
}
