// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: time_entries.sql

package sqlc

import (
	"context"
)

const createTimeEntry = `-- name: CreateTimeEntry :exec
INSERT INTO time_entries (id, task_id, user_id, description, started_at, ended_at, duration_minutes)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTimeEntryParams struct {
	ID              string
	TaskID          string
	UserID          string
	Description     string
	StartedAt       string
	EndedAt         *string
	DurationMinutes *int64
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, createTimeEntry,
		arg.ID,
		arg.TaskID,
		arg.UserID,
		arg.Description,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMinutes,
	)
	return err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entries WHERE id = ? AND task_id = ?
`

type DeleteTimeEntryParams struct {
	ID     string
	TaskID string
}

func (q *Queries) DeleteTimeEntry(ctx context.Context, arg DeleteTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteTimeEntry, arg.ID, arg.TaskID)
	return err
}

const getActiveTimer = `-- name: GetActiveTimer :one
SELECT id, task_id, user_id, description, started_at, ended_at, duration_minutes, created_at, updated_at
FROM time_entries WHERE task_id = ? AND user_id = ? AND ended_at IS NULL LIMIT 1
`

type GetActiveTimerParams struct {
	TaskID string
	UserID string
}

func (q *Queries) GetActiveTimer(ctx context.Context, arg GetActiveTimerParams) (TimeEntry, error) {
	row := q.db.QueryRowContext(ctx, getActiveTimer, arg.TaskID, arg.UserID)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Description,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTimerByUser = `-- name: GetActiveTimerByUser :many
SELECT id, task_id, user_id, description, started_at, ended_at, duration_minutes, created_at, updated_at
FROM time_entries WHERE user_id = ? AND ended_at IS NULL
`

func (q *Queries) GetActiveTimerByUser(ctx context.Context, userID string) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTimerByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Description,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, task_id, user_id, description, started_at, ended_at, duration_minutes, created_at, updated_at
FROM time_entries WHERE task_id = ? ORDER BY started_at DESC
`

func (q *Queries) ListTimeEntries(ctx context.Context, taskID string) ([]TimeEntry, error) {
	rows, err := q.db.QueryContext(ctx, listTimeEntries, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Description,
			&i.StartedAt,
			&i.EndedAt,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTimer = `-- name: StartTimer :exec
INSERT INTO time_entries (id, task_id, user_id, description, started_at)
VALUES (?, ?, ?, ?, datetime('now'))
`

type StartTimerParams struct {
	ID          string
	TaskID      string
	UserID      string
	Description string
}

func (q *Queries) StartTimer(ctx context.Context, arg StartTimerParams) error {
	_, err := q.db.ExecContext(ctx, startTimer,
		arg.ID,
		arg.TaskID,
		arg.UserID,
		arg.Description,
	)
	return err
}

const stopActiveTimersForUser = `-- name: StopActiveTimersForUser :exec
UPDATE time_entries
SET ended_at = datetime('now'),
    duration_minutes = CAST(ROUND((julianday('now') - julianday(started_at)) * 24 * 60) AS INTEGER),
    updated_at = datetime('now')
WHERE user_id = ? AND ended_at IS NULL
`

func (q *Queries) StopActiveTimersForUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, stopActiveTimersForUser, userID)
	return err
}

const stopTimer = `-- name: StopTimer :exec
UPDATE time_entries
SET ended_at = datetime('now'),
    duration_minutes = CAST(ROUND((julianday('now') - julianday(started_at)) * 24 * 60) AS INTEGER),
    updated_at = datetime('now')
WHERE id = ? AND user_id = ? AND ended_at IS NULL
`

type StopTimerParams struct {
	ID     string
	UserID string
}

func (q *Queries) StopTimer(ctx context.Context, arg StopTimerParams) error {
	_, err := q.db.ExecContext(ctx, stopTimer, arg.ID, arg.UserID)
	return err
}

const totalTimeByTask = `-- name: TotalTimeByTask :one
SELECT COALESCE(SUM(duration_minutes), 0) FROM time_entries WHERE task_id = ? AND duration_minutes IS NOT NULL
`

func (q *Queries) TotalTimeByTask(ctx context.Context, taskID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, totalTimeByTask, taskID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateTimeEntry = `-- name: UpdateTimeEntry :exec
UPDATE time_entries
SET description = ?, started_at = ?, ended_at = ?, duration_minutes = ?, updated_at = datetime('now')
WHERE id = ? AND task_id = ?
`

type UpdateTimeEntryParams struct {
	Description     string
	StartedAt       string
	EndedAt         *string
	DurationMinutes *int64
	ID              string
	TaskID          string
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) error {
	_, err := q.db.ExecContext(ctx, updateTimeEntry,
		arg.Description,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationMinutes,
		arg.ID,
		arg.TaskID,
	)
	return err
}
