// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package sqlc

import (
	"context"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT user_id, theme, language, timezone, email_notifications, desktop_notifications, notification_sounds, sidebar_collapsed, motion_settings, created_at, updated_at FROM user_preferences WHERE user_id = ?
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID string) (UserPreference, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.UserID,
		&i.Theme,
		&i.Language,
		&i.Timezone,
		&i.EmailNotifications,
		&i.DesktopNotifications,
		&i.NotificationSounds,
		&i.SidebarCollapsed,
		&i.MotionSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (
    user_id, theme, language, timezone,
    email_notifications, desktop_notifications, notification_sounds,
    sidebar_collapsed, motion_settings
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9
)
ON CONFLICT(user_id) DO UPDATE SET
    theme                = excluded.theme,
    language             = excluded.language,
    timezone             = excluded.timezone,
    email_notifications  = excluded.email_notifications,
    desktop_notifications = excluded.desktop_notifications,
    notification_sounds  = excluded.notification_sounds,
    sidebar_collapsed    = excluded.sidebar_collapsed,
    motion_settings      = excluded.motion_settings,
    updated_at           = datetime('now')
`

type UpsertUserPreferencesParams struct {
	UserID               string
	Theme                string
	Language             string
	Timezone             string
	EmailNotifications   int64
	DesktopNotifications int64
	NotificationSounds   int64
	SidebarCollapsed     int64
	MotionSettings       string
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreferences,
		arg.UserID,
		arg.Theme,
		arg.Language,
		arg.Timezone,
		arg.EmailNotifications,
		arg.DesktopNotifications,
		arg.NotificationSounds,
		arg.SidebarCollapsed,
		arg.MotionSettings,
	)
	return err
}
