// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"strings"
)

const countOwners = `-- name: CountOwners :one
SELECT COUNT(*) as count FROM users WHERE org_id = ? AND role = 'owner' AND is_active = 1
`

func (q *Queries) CountOwners(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwners, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, account_id, org_id, email, name, role, avatar_url, is_active)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	AccountID *string
	OrgID     string
	Email     string
	Name      string
	Role      string
	AvatarUrl *string
	IsActive  int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.AccountID,
		arg.OrgID,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.AvatarUrl,
		arg.IsActive,
	)
	return err
}

const getByOrgAndAccount = `-- name: GetByOrgAndAccount :one
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE org_id = ? AND account_id = ?
`

type GetByOrgAndAccountParams struct {
	OrgID     string
	AccountID *string
}

func (q *Queries) GetByOrgAndAccount(ctx context.Context, arg GetByOrgAndAccountParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getByOrgAndAccount, arg.OrgID, arg.AccountID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE org_id = ? AND email = ?
`

type GetUserByEmailParams struct {
	OrgID string
	Email string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.OrgID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAnyOrg = `-- name: GetUserByEmailAnyOrg :one
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE email = ?
LIMIT 1
`

func (q *Queries) GetUserByEmailAnyOrg(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailAnyOrg, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE id = ? AND org_id = ?
`

type GetUserByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, arg.ID, arg.OrgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByAccount = `-- name: ListUsersByAccount :many
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE account_id = ?
ORDER BY updated_at DESC
`

func (q *Queries) ListUsersByAccount(ctx context.Context, accountID *string) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []string) ([]User, error) {
	query := listUsersByIDs
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersPaginated = `-- name: ListUsersPaginated :many
SELECT id, account_id, org_id, email, name, role, avatar_url, is_active, created_at, updated_at
FROM users
WHERE org_id = ?1

  AND (?2 IS NULL OR ?2 = '' OR instr(lower(name), lower(?2)) > 0)
  AND (?3 IS NULL OR ?3 = '' OR role = ?3)
  AND (?4 = 1 OR is_active = 1)
  AND (
    (?5 = '' AND ?6 = '')
    OR (name > ?5)
    OR (name = ?5 AND id > ?6)
  )
ORDER BY name ASC, id ASC
LIMIT ?7
`

type ListUsersPaginatedParams struct {
	OrgID           string
	Search          interface{}
	Role            interface{}
	IncludeInactive interface{}
	CursorName      interface{}
	CursorID        interface{}
	LimitVal        int64
}

func (q *Queries) ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsersPaginated,
		arg.OrgID,
		arg.Search,
		arg.Role,
		arg.IncludeInactive,
		arg.CursorName,
		arg.CursorID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.OrgID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountProfile = `-- name: UpdateAccountProfile :exec
UPDATE users
SET name = ?, avatar_url = ?, updated_at = datetime('now')
WHERE account_id = ?
`

type UpdateAccountProfileParams struct {
	Name      string
	AvatarUrl *string
	AccountID *string
}

// Syncs the denormalized display columns (name, avatar_url) across ALL of an
// account's memberships so every workspace sees the same identity.
func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountProfile, arg.Name, arg.AvatarUrl, arg.AccountID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?, email = ?, avatar_url = ?, role = ?, is_active = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateUserParams struct {
	Name      string
	Email     string
	AvatarUrl *string
	Role      string
	IsActive  int64
	ID        string
	OrgID     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.Role,
		arg.IsActive,
		arg.ID,
		arg.OrgID,
	)
	return err
}

const updateUserActive = `-- name: UpdateUserActive :exec
UPDATE users
SET is_active = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateUserActiveParams struct {
	IsActive int64
	ID       string
	OrgID    string
}

func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateUserActive, arg.IsActive, arg.ID, arg.OrgID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = ?, updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateUserRoleParams struct {
	Role  string
	ID    string
	OrgID string
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID, arg.OrgID)
	return err
}
