// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: views.sql

package sqlc

import (
	"context"
)

const createView = `-- name: CreateView :exec
INSERT INTO views (id, org_id, project_id, created_by, name, layout, filters)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateViewParams struct {
	ID        string
	OrgID     string
	ProjectID *string
	CreatedBy string
	Name      string
	Layout    string
	Filters   string
}

func (q *Queries) CreateView(ctx context.Context, arg CreateViewParams) error {
	_, err := q.db.ExecContext(ctx, createView,
		arg.ID,
		arg.OrgID,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Name,
		arg.Layout,
		arg.Filters,
	)
	return err
}

const deleteView = `-- name: DeleteView :exec
DELETE FROM views WHERE id = ? AND org_id = ?
`

type DeleteViewParams struct {
	ID    string
	OrgID string
}

func (q *Queries) DeleteView(ctx context.Context, arg DeleteViewParams) error {
	_, err := q.db.ExecContext(ctx, deleteView, arg.ID, arg.OrgID)
	return err
}

const getViewByID = `-- name: GetViewByID :one
SELECT id, org_id, project_id, created_by, name, layout, filters, created_at, updated_at
FROM views
WHERE id = ? AND org_id = ?
`

type GetViewByIDParams struct {
	ID    string
	OrgID string
}

func (q *Queries) GetViewByID(ctx context.Context, arg GetViewByIDParams) (View, error) {
	row := q.db.QueryRowContext(ctx, getViewByID, arg.ID, arg.OrgID)
	var i View
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Name,
		&i.Layout,
		&i.Filters,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGlobalViews = `-- name: ListGlobalViews :many
SELECT id, org_id, project_id, created_by, name, layout, filters, created_at, updated_at
FROM views
WHERE org_id = ?
  AND project_id IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListGlobalViews(ctx context.Context, orgID string) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalViews, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Name,
			&i.Layout,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPinnedViews = `-- name: ListPinnedViews :many
SELECT v.id, v.org_id, v.project_id, v.created_by, v.name, v.layout, v.filters, v.created_at, v.updated_at
FROM views v
JOIN view_pins vp ON vp.view_id = v.id
WHERE vp.user_id = ?
ORDER BY vp.created_at DESC
`

func (q *Queries) ListPinnedViews(ctx context.Context, userID string) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listPinnedViews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Name,
			&i.Layout,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsByProject = `-- name: ListViewsByProject :many
SELECT id, org_id, project_id, created_by, name, layout, filters, created_at, updated_at
FROM views
WHERE org_id = ?1
  AND project_id = ?2
ORDER BY created_at ASC
`

type ListViewsByProjectParams struct {
	OrgID     string
	ProjectID *string
}

func (q *Queries) ListViewsByProject(ctx context.Context, arg ListViewsByProjectParams) ([]View, error) {
	rows, err := q.db.QueryContext(ctx, listViewsByProject, arg.OrgID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []View
	for rows.Next() {
		var i View
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ProjectID,
			&i.CreatedBy,
			&i.Name,
			&i.Layout,
			&i.Filters,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pinView = `-- name: PinView :exec
INSERT OR IGNORE INTO view_pins (view_id, user_id) VALUES (?, ?)
`

type PinViewParams struct {
	ViewID string
	UserID string
}

func (q *Queries) PinView(ctx context.Context, arg PinViewParams) error {
	_, err := q.db.ExecContext(ctx, pinView, arg.ViewID, arg.UserID)
	return err
}

const unpinView = `-- name: UnpinView :exec
DELETE FROM view_pins WHERE view_id = ? AND user_id = ?
`

type UnpinViewParams struct {
	ViewID string
	UserID string
}

func (q *Queries) UnpinView(ctx context.Context, arg UnpinViewParams) error {
	_, err := q.db.ExecContext(ctx, unpinView, arg.ViewID, arg.UserID)
	return err
}

const updateView = `-- name: UpdateView :exec
UPDATE views
SET name = ?,
    layout = ?,
    filters = ?,
    updated_at = datetime('now')
WHERE id = ? AND org_id = ?
`

type UpdateViewParams struct {
	Name    string
	Layout  string
	Filters string
	ID      string
	OrgID   string
}

func (q *Queries) UpdateView(ctx context.Context, arg UpdateViewParams) error {
	_, err := q.db.ExecContext(ctx, updateView,
		arg.Name,
		arg.Layout,
		arg.Filters,
		arg.ID,
		arg.OrgID,
	)
	return err
}
