// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voice.sql

package sqlc

import (
	"context"
)

const countVoiceParticipants = `-- name: CountVoiceParticipants :one
SELECT COUNT(*) FROM voice_participants
WHERE conversation_id = ? AND org_id = ?
`

type CountVoiceParticipantsParams struct {
	ConversationID string
	OrgID          string
}

func (q *Queries) CountVoiceParticipants(ctx context.Context, arg CountVoiceParticipantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countVoiceParticipants, arg.ConversationID, arg.OrgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllVoiceParticipants = `-- name: DeleteAllVoiceParticipants :execrows
DELETE FROM voice_participants
`

// Startup sweep: voice_participants rows are in-memory session state that
// outlives the process on a crash. Any row at boot refers to a connection
// that no longer exists.
func (q *Queries) DeleteAllVoiceParticipants(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAllVoiceParticipants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getVoiceParticipant = `-- name: GetVoiceParticipant :one
SELECT id, conversation_id, org_id, user_id, muted, deafened, connection_id, joined_at
FROM voice_participants
WHERE conversation_id = ? AND user_id = ? AND org_id = ?
`

type GetVoiceParticipantParams struct {
	ConversationID string
	UserID         string
	OrgID          string
}

func (q *Queries) GetVoiceParticipant(ctx context.Context, arg GetVoiceParticipantParams) (VoiceParticipant, error) {
	row := q.db.QueryRowContext(ctx, getVoiceParticipant, arg.ConversationID, arg.UserID, arg.OrgID)
	var i VoiceParticipant
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.OrgID,
		&i.UserID,
		&i.Muted,
		&i.Deafened,
		&i.ConnectionID,
		&i.JoinedAt,
	)
	return i, err
}

const joinVoiceChannel = `-- name: JoinVoiceChannel :exec
INSERT INTO voice_participants (id, conversation_id, org_id, user_id, muted, deafened, connection_id)
VALUES (?, ?, ?, ?, 0, 0, ?)
`

type JoinVoiceChannelParams struct {
	ID             string
	ConversationID string
	OrgID          string
	UserID         string
	ConnectionID   string
}

func (q *Queries) JoinVoiceChannel(ctx context.Context, arg JoinVoiceChannelParams) error {
	_, err := q.db.ExecContext(ctx, joinVoiceChannel,
		arg.ID,
		arg.ConversationID,
		arg.OrgID,
		arg.UserID,
		arg.ConnectionID,
	)
	return err
}

const leaveVoiceChannel = `-- name: LeaveVoiceChannel :exec
DELETE FROM voice_participants
WHERE conversation_id = ? AND user_id = ? AND org_id = ?
`

type LeaveVoiceChannelParams struct {
	ConversationID string
	UserID         string
	OrgID          string
}

func (q *Queries) LeaveVoiceChannel(ctx context.Context, arg LeaveVoiceChannelParams) error {
	_, err := q.db.ExecContext(ctx, leaveVoiceChannel, arg.ConversationID, arg.UserID, arg.OrgID)
	return err
}

const listActiveVoiceForUser = `-- name: ListActiveVoiceForUser :many
SELECT id, conversation_id, org_id, user_id, muted, deafened, connection_id, joined_at
FROM voice_participants WHERE user_id = ? AND org_id = ?
`

type ListActiveVoiceForUserParams struct {
	UserID string
	OrgID  string
}

func (q *Queries) ListActiveVoiceForUser(ctx context.Context, arg ListActiveVoiceForUserParams) ([]VoiceParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listActiveVoiceForUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceParticipant
	for rows.Next() {
		var i VoiceParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.UserID,
			&i.Muted,
			&i.Deafened,
			&i.ConnectionID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceParticipants = `-- name: ListVoiceParticipants :many
SELECT id, conversation_id, org_id, user_id, muted, deafened, connection_id, joined_at
FROM voice_participants
WHERE conversation_id = ? AND org_id = ?
ORDER BY joined_at ASC
`

type ListVoiceParticipantsParams struct {
	ConversationID string
	OrgID          string
}

func (q *Queries) ListVoiceParticipants(ctx context.Context, arg ListVoiceParticipantsParams) ([]VoiceParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listVoiceParticipants, arg.ConversationID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceParticipant
	for rows.Next() {
		var i VoiceParticipant
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.UserID,
			&i.Muted,
			&i.Deafened,
			&i.ConnectionID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoiceParticipantsWithUser = `-- name: ListVoiceParticipantsWithUser :many
SELECT vp.id, vp.conversation_id, vp.org_id, vp.user_id, vp.muted, vp.deafened, vp.connection_id, vp.joined_at,
       u.name AS user_name, u.avatar_url AS user_avatar_url
FROM voice_participants vp
JOIN users u ON u.id = vp.user_id AND u.org_id = vp.org_id
WHERE vp.conversation_id = ? AND vp.org_id = ?
ORDER BY vp.joined_at ASC
`

type ListVoiceParticipantsWithUserParams struct {
	ConversationID string
	OrgID          string
}

type ListVoiceParticipantsWithUserRow struct {
	ID             string
	ConversationID string
	OrgID          string
	UserID         string
	Muted          int64
	Deafened       int64
	ConnectionID   string
	JoinedAt       string
	UserName       string
	UserAvatarUrl  *string
}

func (q *Queries) ListVoiceParticipantsWithUser(ctx context.Context, arg ListVoiceParticipantsWithUserParams) ([]ListVoiceParticipantsWithUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listVoiceParticipantsWithUser, arg.ConversationID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoiceParticipantsWithUserRow
	for rows.Next() {
		var i ListVoiceParticipantsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.OrgID,
			&i.UserID,
			&i.Muted,
			&i.Deafened,
			&i.ConnectionID,
			&i.JoinedAt,
			&i.UserName,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVoiceConnection = `-- name: UpdateVoiceConnection :exec
UPDATE voice_participants
SET connection_id = ?
WHERE conversation_id = ? AND user_id = ? AND org_id = ?
`

type UpdateVoiceConnectionParams struct {
	ConnectionID   string
	ConversationID string
	UserID         string
	OrgID          string
}

// Reassign a participant's owning connection (used when a tab takes over an
// existing voice session).
func (q *Queries) UpdateVoiceConnection(ctx context.Context, arg UpdateVoiceConnectionParams) error {
	_, err := q.db.ExecContext(ctx, updateVoiceConnection,
		arg.ConnectionID,
		arg.ConversationID,
		arg.UserID,
		arg.OrgID,
	)
	return err
}

const updateVoiceFlags = `-- name: UpdateVoiceFlags :exec
UPDATE voice_participants
SET muted = ?, deafened = ?
WHERE conversation_id = ? AND user_id = ? AND org_id = ?
`

type UpdateVoiceFlagsParams struct {
	Muted          int64
	Deafened       int64
	ConversationID string
	UserID         string
	OrgID          string
}

func (q *Queries) UpdateVoiceFlags(ctx context.Context, arg UpdateVoiceFlagsParams) error {
	_, err := q.db.ExecContext(ctx, updateVoiceFlags,
		arg.Muted,
		arg.Deafened,
		arg.ConversationID,
		arg.UserID,
		arg.OrgID,
	)
	return err
}
